BusOne/src/objects/Account_Plan_vod__c.object
<CustomObject>
    <description>This object stores all Account Plan header data</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to store the channel value.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>MCO Confirmed</fullName>
                </value>
                <value>
                    <fullName>PBMReport</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Product_Type__c</fullName>
        <description>Used to store the product type name.</description>
        <label>Product Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <recordTypes>
        <fullName>PBM</fullName>
        <active>true</active>
        <description>Used for PBM Plan Demographies</description>
        <label>PBM</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <description>Benefit Design represents a Benefit Design for a specific Managed Care (Payer) account. There may be multiple Benefit Designs for a particular account. Benefit Design Line is a child object of Benefit Design.</description>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to store the name of the channel</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Copay__c</fullName>
        <description>Used to store the co pay values</description>
        <label>Copay</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>To store the BOT formulary ID</description>
        <label>Formulary ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related formulary</description>
        <label>Formulary Product</label>
        <referenceTo>Formulary_Products_vod__c</referenceTo>
        <relationshipLabel>Benefit Designs</relationshipLabel>
        <relationshipName>Benefit_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related Plan Demographies</description>
        <label>Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Benefit Designs</relationshipLabel>
        <relationshipName>Benefit_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Type__c</fullName>
        <formula>BOT_Product_Plan__r.BOT_Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <label>Benefit Design</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account plan.</description>
        <label>Plan Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to display the channel</description>
        <formula>TEXT( BOT_Account_Plan__r.BOT_Channel__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Copay__c</fullName>
        <description>To store the copay for the selected Formulary benefit design</description>
        <label>Copay</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <description>Used to store the name of the Formulary.</description>
        <label>Formulary Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Type__c</fullName>
        <description>Used to store the Product type of the associated Plan Product</description>
        <formula>BOT_Account_Plan__r.BOT_Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Status__c</fullName>
        <description>To store the status for Formulary benefit design</description>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/objects/Product_vod__c.object
<CustomObject>
    <description>The Product Catalog</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup relationship to account</description>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account</relationshipLabel>
        <relationshipName>BOT_Account_Drug</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Copay__c</fullName>
        <description>Used to store the value of the copay</description>
        <label>Copay</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Status__c</fullName>
        <description>Used to display the status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Non-Preferred</fullName>
                </value>
                <value>
                    <fullName>Non-Preferred Brand</fullName>
                </value>
                <value>
                    <fullName>Non-Preferred Generic</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Not Listed</fullName>
                </value>
                <value>
                    <fullName>Preferred Brand</fullName>
                </value>
                <value>
                    <fullName>Preferred Generic</fullName>
                </value>
                <value>
                    <fullName>Specialty</fullName>
                </value>
                <value>
                    <fullName>Specialty Non-Preferred</fullName>
                </value>
                <value>
                    <fullName>Specialty Preferred</fullName>
                </value>
                <value>
                    <fullName>Tier 4</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>NL</fullName>
                </value>
                <value>
                    <fullName>NP</fullName>
                </value>
                <value>
                    <fullName>NPB</fullName>
                </value>
                <value>
                    <fullName>NPG</fullName>
                </value>
                <value>
                    <fullName>PB</fullName>
                </value>
                <value>
                    <fullName>PG</fullName>
                </value>
                <value>
                    <fullName>T4</fullName>
                </value>
                <value>
                    <fullName>Preferred</fullName>
                </value>
                <value>
                    <fullName>Reimbursed</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>S-NP</fullName>
                </value>
                <value>
                    <fullName>S-P</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Therapeutic_Class_vod__c</fullName>
        <description>Picklist used to select the Therapeutic Class of the product such as Narcotics or Pain Relief. Therapeutic Class is controlled by the Therapeutic Area picklist.</description>
        <label>Therapeutic Class</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Therapeutic_Area_vod__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Anti-Inflammatory Medicines (NSAIDs)</fullName>
                </value>
                <value>
                    <fullName>Cox-2 Inhibitors</fullName>
                </value>
                <value>
                    <fullName>Muscle Relaxants</fullName>
                </value>
                <value>
                    <fullName>Narcotics</fullName>
                </value>
                <value>
                    <fullName>Pain Relief</fullName>
                </value>
                <value>
                    <fullName>Antianginals</fullName>
                </value>
                <value>
                    <fullName>Antiarrhythmics</fullName>
                </value>
                <value>
                    <fullName>Anticoagulants (Blood Thinners)</fullName>
                </value>
                <value>
                    <fullName>CHF Agents</fullName>
                </value>
                <value>
                    <fullName>Diuretics (Combination &quot;Water&quot; Pills)</fullName>
                </value>
                <value>
                    <fullName>Diuretics (&quot;Water&quot; Pills)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (ACE Inhibitors)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Alpha Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Angiotensin Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Beta-blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Calcium Channel Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Combination ACE Inhibitors)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Combination Angiotensin Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Combination Beta-blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Combination Calcium Channel Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Long-acting Calcium Channel Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Miscellaneous)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Miscellaneous Combination Products )</fullName>
                </value>
                <value>
                    <fullName>High Cholesterol (Others)</fullName>
                </value>
                <value>
                    <fullName>High Cholesterol (Statins)</fullName>
                </value>
                <value>
                    <fullName>Vasodilators</fullName>
                </value>
                <value>
                    <fullName>Acne</fullName>
                </value>
                <value>
                    <fullName>Foot Ulcers</fullName>
                </value>
                <value>
                    <fullName>Hair Loss</fullName>
                </value>
                <value>
                    <fullName>Topical Antibiotics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Catalog</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_Drug_View_Extn.cls
/*
Name:BOT_Drug_View_Extn
Created By :Harsha BR
Created Date:02/27/2017
Overview:Used to display the Drug data.

Modified By: Harsha BR
Modified Date: 04/04/2017
Reason: To add Pagination
*/

public class BOT_Drug_View_Extn 
{
     Public ID formularyId{get;set;}                                        //Used to store the Formulary record ID
     Public string selected{get;set;}                                       //Used to store the selected Therapeutic Class value
     Public String botFormID{get;set;}                                      //Used to store the BOT Formulary ID
     Public String botPlanProdID{get;set;}                                  //Used to store the BOT Plan Product ID
     Public String accName{get;set;}										//Used to store the Account Name
     Public Boolean blnPBMAcc{get;set;}										//True if the Account type is not PBM 	
     public set<String> setTherapeutic = new set<String>();                 //Used to store the Therapeutic Class
     Public List<Product_vod__c> lstProducts{get;set;}                      //Used to store the Drug data 
     Public List<Formulary_Products_vod__c> lstDesigns{get;set;}            //Used to store the Benefit design data
     Private static final integer list_size=10;        						//sets the page size or number of rows
     Private integer counter=0;                      						//keeps track of the offset 
     Public integer total_size{get;set;}                          			//Used to show user the total size of the list
     Private string strFilter;												//Used to store the condition to run the query
	 Private string firstThera;												//Used to store the First Therapeutic class Name 
     Private string strExeQuery;											//Used to store the query to find the number of drug records
     Public Boolean blnButtons{get;set;}
    
    //Constructor
    Public BOT_Drug_View_Extn(ApexPages.StandardController controller) 
    {
        formularyId = controller.getRecord().Id;
        strFilter='';
        fetchProducts();
    }
    

    //Used to fetch all the Events associated with the account.
    Public void fetchProducts()
    { 
        String strAccType;
        List<Product_vod__c> lstTherapeutic=new List<Product_vod__c>();		//To store the therapeutic class
        
        List<Formulary_Products_vod__c> lstForms=[SELECT ID,Name,BOT_Account__r.Account_Type__c,BOT_Account__r.Name,BOT_Account_Plan__c
                                                  FROM Formulary_Products_vod__c
                                                  WHERE ID=:formularyId
                                                  LIMIT 1];
        
        if(!lstForms.isEmpty())
        {
            if(lstForms[0].name!='')
            {
             	botFormID=lstForms[0].name;   
            }
            
            if(lstForms[0].BOT_Account__r.Account_Type__c!=null)
            {
             	strAccType=lstForms[0].BOT_Account__r.Account_Type__c;   
            } 
            if(lstForms[0].BOT_Account_Plan__c!=null)
            {
                botPlanProdID=lstForms[0].BOT_Account_Plan__c;
            }
            if(lstForms[0].BOT_Account__r.Name!=null)
            {
                accName=lstForms[0].BOT_Account__r.Name;
            }
        }
        
        if(strAccType!='PBM')
        {
        	blnPBMAcc=true; 	   
        }
        //Used to query the Benefit design data
        lstDesigns=[SELECT Id,BOT_Formulary_Name__c, (SELECT Id,Name,BOT_Channel__c,BOT_Copay__c,BOT_Status__c,BOT_Product_Type__c,BOT_Product_Plan__r.Name,BOT_Formulary__c,BOT_Formulary__r.BOT_Formulary_Name__c
                    FROM Benefit_Designs__r)
                    FROM Formulary_Products_vod__c
                    WHERE Id=:formularyId and Id in (SELECT BOT_Formulary__c from Benefit_Design_vod__c)
                    LIMIT 50000];
        
         lstTherapeutic=[SELECT Id,Therapeutic_Class_vod__c,BOT_Formulary_ID__c
                         FROM Product_vod__c
                     	 WHERE BOT_Formulary_ID__c=:botFormID
                     	 ORDER BY Therapeutic_Class_vod__c 
                     	 LIMIT 50000];
        
        for(Product_vod__c objProd:lstTherapeutic)
        {
            if(objProd.Therapeutic_Class_vod__c!='')
            {
            	setTherapeutic.add(objProd.Therapeutic_Class_vod__c);    
            }     
        }
        
        if(!setTherapeutic.isEmpty())
        {
        	firstThera= new List<String> (setTherapeutic)[0];    
        }
        
        strFilter='BOT_Formulary_ID__c=:botFormID AND Therapeutic_Class_vod__c=:firstThera AND BOT_Plan_Demographics__c=:botPlanProdID';
        
        String strCountQuery = 'Select Count() From Product_vod__c Where ' + strFilter;
        total_size = database.Countquery(strCountQuery);
		if(total_size>0)
        {
            if(total_size<list_size)
            {
                blnButtons=false;
            }
            else
            {
            	 blnButtons=true;
            }
        	strExeQuery ='SELECT Id,Name,BOT_Formulary_ID__c,Therapeutic_Class_vod__c,BOT_Status__c,Restricted_States_vod__c,BOT_Copay__c,BOT_Strength__c FROM Product_vod__c WHERE BOT_Formulary_ID__c=:botFormID AND Therapeutic_Class_vod__c =:firstThera AND BOT_Plan_Demographics__c=:botPlanProdID ORDER BY Name ';
        	fetchDrugs();    
        }
    }

    //Used to filter the drug based based on the selected therapeutic class
    Public void fetchResults()
    {
        counter=0;
		strFilter='BOT_Formulary_ID__c=:botFormID AND Therapeutic_Class_vod__c=:selected AND BOT_Plan_Demographics__c=:botPlanProdID';
        String strCountQuery = 'Select Count() From Product_vod__c Where ' + strFilter;
        total_size = database.Countquery(strCountQuery);
        if(total_size>0)
        {
            if(total_size<list_size)
            {
                blnButtons=false;
            }
            else
            {
				blnButtons=true;
            }
        	strExeQuery ='SELECT Id,Name,BOT_Formulary_ID__c,Therapeutic_Class_vod__c,BOT_Status__c,Restricted_States_vod__c,BOT_Copay__c,BOT_Strength__c FROM Product_vod__c WHERE BOT_Formulary_ID__c=:botFormID AND Therapeutic_Class_vod__c =:selected AND BOT_Plan_Demographics__c=:botPlanProdID ORDER BY Name';
        	fetchDrugs();    
        }	
    }
    
    //Used to query the drug data
    Public void fetchDrugs()
    {
         lstProducts= database.query(strExeQuery);  
    }
    
    //Used to store the therapeutic class values
    Public List<SelectOption> getdynamiclist()
    {
        List<SelectOption> options = new List<SelectOption>();

        for(String value : setTherapeutic)
        {
            options.add(new SelectOption(value,value));
        }
        return options;
    }
    
    //This will disable the previous and first buttons
    Public Boolean getDisablePrevious() 
    { 
        if (counter>0)
        {
            return false; 
        }
        else
        {
            return true;
        }
    }
    
    //This will disable the next and last buttons
    public Boolean getDisableNext() 
    { 
        if (counter + list_size < total_size) 
        {
            return false; 
        }
        else
        {
            return true;
        }
    }
    
    //User clicked First button
    Public PageReference first()
    {
        counter = 0;
        fetchDrugs();
        return null;
    }
    
    //User clicked previous button
    Public PageReference Previous()
    {
        counter -= list_size;
        fetchDrugs();
        return null;
    }
    
    //User clicked next button
    Public PageReference Next()
    {
        counter += list_size;
        fetchDrugs();
        return null;
    }
    
    ///User clicked end button
    Public PageReference last()
    {
        counter = total_size - math.mod(total_size, list_size);
        if(counter==total_size)
        {
            counter-=list_size;
        }
        fetchDrugs();
        return null;
    }
    
    Public Integer getPageNumber() 
    {
		return counter/list_size + 1;
    }

    Public Integer getTotalPages() 
    {
       if(math.mod(total_size, list_size) > 0)
       {
			return total_size/list_size + 1;
       } 
       else
       {
			return (total_size/list_size); 
       }
   }
}