BusOne/src/objects/Account_Plan_vod__c.object
<CustomObject>
    <description>This object stores all Account Plan header data</description>
    <fields>
        <fullName>Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to master account.</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <description>Benefit Design represents a Benefit Design for a specific Managed Care (Payer) account. There may be multiple Benefit Designs for a particular account. Benefit Design Line is a child object of Benefit Design.</description>
    <fields>
        <fullName>Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that this Benefit Design belongs to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Designs</relationshipLabel>
        <relationshipName>Account_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>To store the BOT formulary ID</description>
        <label>Formulary ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related formulary</description>
        <label>Formulary Product</label>
        <referenceTo>Formulary_Products_vod__c</referenceTo>
        <relationshipLabel>Benefit Designs</relationshipLabel>
        <relationshipName>Benefit_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related Plan Demographies</description>
        <label>Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Benefit Designs</relationshipLabel>
        <relationshipName>Benefit_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <label>Benefit Design</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account plan.</description>
        <label>Plan Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_BenifitDesign_RelField_Update_Test.cls
/* 
Name            : BOT_BenifitDesign_RelField_Update_Test
Created by      : Sreenivasulu Adipudi
Created Date    : 06/Mar/2017
Description     : This test class is used to test the trigger class (BOT_BDesign_RelField_Update_Handler) 
*/
@isTest(seeAllData=False)
public class BOT_BenifitDesign_RelField_Update_Test 
{
    public static testMethod void BOT_BenifitDesign_RelField_Update()
    {
        //inserting a record into account object
        Account acc = new Account();
        acc.name = 'Test Acc1';
        insert acc;
        //inserting a record into plan demographics object with account id
        Account_Plan_vod__c plan = new Account_Plan_vod__c();
        plan.name = 'Test Plan1';
        plan.Account_vod__c=acc.id;
        insert plan;
        //inserting a record into formulary object with account id and plan id
        Formulary_Products_vod__c form = new Formulary_Products_vod__c();
        form.name='form1';
        form.BOT_Account__c=plan.Account_vod__c;
        form.BOT_Account_Plan__c=plan.id;
        insert form;
        ID tempformularyID=form.Id;
        //inserting a record into Benefit design object with account id,plan id and formulary name (BOT formulary Id)
        Benefit_Design_vod__c ben = new Benefit_Design_vod__c();
        ben.name='ben1';
        ben.Account_vod__c=form.BOT_Account__c;
        ben.BOT_Product_Plan__c=form.BOT_Account_Plan__c;
        ben.BOT_Formulary_ID__c=form.name;
        insert ben;
        //Comparing the BOT formulary Id with formulary Id in Benefit disign
        System.assertEquals('form1', ben.BOT_Formulary_ID__c);
        System.assertEquals(tempformularyID, ben.BOT_Formulary__c);
        System.debug('Formulary Record ID'+tempformularyID);
        System.debug('BenefitDesign Formulary ID'+ben.BOT_Formulary__c);
    }
}