BusOne/src/objects/Account_Plan_vod__c.object
<CustomObject>
    <description>This object stores all Account Plan header data</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to store the channel value.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>MCO Confirmed</fullName>
                </value>
                <value>
                    <fullName>PBMReport</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/Pagenation_sample_extn.cls
public class Pagenation_sample_extn 
{
    Public ID acctID{get;set;}                           								//Used to store the current record id        
    Public string selected{get;set;}                        							//Used to store the selected channel VF page
    Public set<String> picklist;       	 												//Used to store the unique channels
    Public List<Account_Plan_vod__c> plansForChannel = new List<Account_Plan_vod__c>(); //Used to store the related plan demograpics records for the selected account
	//Constructor
    public Pagenation_sample_extn(ApexPages.StandardController controller)
    {
        //Getting the current account Id
        acctID=controller.getRecord().Id;
        //Getting the related plan demographics records based on selected account id
        if(acctID != null)
        {
        	plansForChannel = [select BOT_Account__c,BOT_Channel__c,id,name From Account_Plan_vod__c Where BOT_Account__c =: acctID order by BOT_Channel__c];
        	for(Account_Plan_vod__c st : plansForChannel)
        	{
            	//Getting the unique channel values
            	picklist.add(st.BOT_Channel__c);
        	}
		}        
    }
    public void get_Account_summary()
    {
        
    }
    //Creating chanel selection picklist values
    public List<selectOption> getDynamicList() 
    {
        List<selectOption> options = new List<selectOption>();
        if(picklist.size()>1 && picklist != null)
        {
        	options.add(new selectOption('--All--','--All--'));
        }
        for(String s : picklist)
        {
            //Add the channels to picklist to display on VF Page
            options.add(new selectOption(s,s));
        }
        return options;
    }    
    /*public string selected {get;set;}
    public List<Account_Plan_vod__c> accountsChannel;
    public Id selectedAccountId;
    public set<String> pickList;
    public Pagenation_sample_extn(apexPages.StandardController controller)
    {
        selectedAccountId=controller.getRecord().Id;        
        if(selectedAccountId != null && selectedAccountId != '')
        {
        	accountsChannel = [select BOT_Channel__c,id From Account_Plan_vod__c Where BOT_Account__c =: selectedAccountId order by BOT_Channel__c];
        	for(Account_Plan_vod__c c : accountsChannel)
        	{
            	pickList.add(c.BOT_Channel__c);
        	}
        }
        System.debug('Query records '+accountsChannel);
        System.debug('Selected Record '+selectedAccountId);
        System.debug('Channels '+pickList);
    }
    public void get_Account_summary()
    {
        
    }
    public List<selectOption> getDynamicList()
    {
        List<selectOption> options = new List<selectOption>();
        
        if(pickList.size()>0 && pickList != null)
        {
        	options.add(new selectOption('--All--','--All--'));
        	for(String p : pickList )
        	{
            	options.add(new selectOption(p,p));
        	}
        }
        return options;
    }*/
}