BusOne/src/objects/Account_Plan_vod__c.object
<CustomObject>
    <description>This object stores all Account Plan header data</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to store the channel value.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>MCO Confirmed</fullName>
                </value>
                <value>
                    <fullName>PBMReport</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Used__c</fullName>
        <label>Formulary Used</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_PBM__c</fullName>
        <label>PBM</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Lives_Rx__c</fullName>
        <description>Used to store the Product Lives RX</description>
        <label>Product Lives Rx</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Type__c</fullName>
        <description>Used to store the product type name.</description>
        <label>Product Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/BOT_Pharamcy_Service__c.object
<CustomObject>
    <description>Used to store the data related to the Pharmacy Service</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Pharamcy_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to display the channel</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Corporate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Corporate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BOT_Other_Provider_Name__c</fullName>
        <label>Other Provider Name</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACS Pharm/DUR</fullName>
                </value>
                <value>
                    <fullName>Allscripts</fullName>
                </value>
                <value>
                    <fullName>Avella Specialty Pharmacy</fullName>
                </value>
                <value>
                    <fullName>AxelaCare</fullName>
                </value>
                <value>
                    <fullName>Biologics</fullName>
                </value>
                <value>
                    <fullName>Biologics Inc</fullName>
                </value>
                <value>
                    <fullName>Burman`s Specialty Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Centric Health Resources</fullName>
                </value>
                <value>
                    <fullName>Cystic Fibrosis Services</fullName>
                </value>
                <value>
                    <fullName>Diplomat Specialty Pharmacy</fullName>
                </value>
                <value>
                    <fullName>ePocrates</fullName>
                </value>
                <value>
                    <fullName>Foundation Care</fullName>
                </value>
                <value>
                    <fullName>IVSolutions</fullName>
                </value>
                <value>
                    <fullName>Local Pharmacies</fullName>
                </value>
                <value>
                    <fullName>Option Care</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Specialties Inc</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Surescripts</fullName>
                </value>
                <value>
                    <fullName>US Bioservices Inc</fullName>
                </value>
                <value>
                    <fullName>Wellpartner</fullName>
                </value>
                <value>
                    <fullName>Wellpartner Specialty Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Acro Pharmaceutical Services</fullName>
                </value>
                <value>
                    <fullName>RxCrossroads</fullName>
                </value>
                <value>
                    <fullName>Kroger</fullName>
                </value>
                <value>
                    <fullName>Advanced Care Scripts</fullName>
                </value>
                <value>
                    <fullName>Wellpartner Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Affinity Biotech</fullName>
                </value>
                <value>
                    <fullName>Walgreens</fullName>
                </value>
                <value>
                    <fullName>Kroger Prescription Plans</fullName>
                </value>
                <value>
                    <fullName>AllCare Plus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_PBM_Name__c</fullName>
        <description>Used to store the PBM Name.</description>
        <label>PBM Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Pharmacy Service</label>
    <nameField>
        <label>Pharamcy Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharmacy Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account plan.</description>
        <label>Plan Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to display the channel</description>
        <formula>TEXT( BOT_Account_Plan__r.BOT_Channel__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives__c</fullName>
        <description>Used to store the Formulary lives value</description>
        <label>Total Formulary Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <description>Used to store the name of the Formulary.</description>
        <label>Formulary Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Type__c</fullName>
        <description>Used to store the Product type of the associated Plan Product</description>
        <formula>BOT_Account_Plan__r.BOT_Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Sales_force_SNo__c</fullName>
        <description>To store the Unique Sno for salesforce reference. Because there is no unique value in this object.</description>
        <label>Sales force SNo</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_Account_Related_List.cls
public with sharing class BOT_Account_Related_List {
	//To get channels dynamically
    @AuraEnabled
    public static List<String> getChannels(Id accountId) {
        //List<Account_Plan_vod__c> allChannels = new List<Account_Plan_vod__c>();
        set<String> uniqueChannels = new set<String>();
        List<String> channels = new List<String>();
        //allChannels = [select id, BOT_Channel__c from Account_Plan_vod__c where BOT_Account__c=:accountId order by BOT_Channel__c];
        for(Account_Plan_vod__c plan : [select id, BOT_Channel__c from Account_Plan_vod__c where BOT_Account__c=:accountId order by BOT_Channel__c]) {
            uniqueChannels.add(plan.BOT_Channel__c);
        }
        if(uniqueChannels.size() > 1)
        	channels.add('ALL');
        channels.addAll(uniqueChannels);
        return channels;
    }
    
    //To get Account plan records related to selected account
    @AuraEnabled
    public static AccountPlanWrapper fetchAccountPlans(Decimal pageNumber ,Integer recordToDisply, String channel, Id accountId) {
    	Integer pageSize = recordToDisply;
      	Integer offset = ((Integer)pageNumber - 1) * pageSize;
        // create a instance of wrapper class.
        AccountPlanWrapper plan = new AccountPlanWrapper();
        // set the pageSize,Page(Number), total records and accounts List(using OFFSET)
        plan.pageSize = pageSize;
        plan.page = (Integer) pageNumber;
        if(accountId != null && channel == 'ALL' && channel != '')
        {
        	plan.total = [SELECT count() FROM Account_Plan_vod__c where BOT_Account__c=:accountId];
        	plan.accountPlans = [select Id, BOT_Channel__c, Name, BOT_Product_Type__c, BOT_Formulary_Used__c, BOT_PBM__c, 
                     			BOT_Product_Lives_Rx__c from Account_Plan_vod__c where BOT_Account__c=:accountId order by BOT_Channel__c 
                                LIMIT :recordToDisply OFFSET :offset];
        }
        else if(accountId != null && channel != '')
        {
			plan.total = [SELECT count() FROM Account_Plan_vod__c where BOT_Account__c=:accountId and BOT_Channel__c=:channel];
        	plan.accountPlans = [select Id, BOT_Channel__c, Name, BOT_Product_Type__c, BOT_Formulary_Used__c, BOT_PBM__c, 
                     			BOT_Product_Lives_Rx__c from Account_Plan_vod__c where BOT_Account__c=:accountId and BOT_Channel__c=:channel 
                                order by BOT_Channel__c LIMIT :recordToDisply OFFSET :offset];            
        }
        // return the wrapper class instance .
        return plan;
    }
    
    //To get Formulary records related to selected account
    @AuraEnabled
    public static AccountFormularyWrapper fetchAccountFormulary(Decimal pageNumber ,Integer formularyRecordToDisplay, String channel, Id accountId) {
    	Integer pageSize = formularyRecordToDisplay;
      	Integer offset = ((Integer)pageNumber - 1) * pageSize;
        // create a instance of wrapper class.
        AccountFormularyWrapper form = new AccountFormularyWrapper();
        // set the pageSize,Page(Number), total records and accounts List(using OFFSET)
        form.pageSize = pageSize;
        form.page = (Integer) pageNumber;
        if(accountId != null && channel == 'ALL' && channel != '')
        {
        	form.total = [SELECT count() FROM Formulary_Products_vod__c where BOT_Account__c=:accountId];
        	form.accountFormulary = [select Id, BOT_Channel__c, BOT_Formulary_Name__c, BOT_Product_Type__c, BOT_Account_Plan__r.Name, 
                         			BOT_Formulary_Lives__c, BOT_Sales_force_SNo__c from Formulary_Products_vod__c where 
                                    BOT_Account__c=:accountId order by BOT_Channel__c LIMIT :formularyRecordToDisplay OFFSET :offset];
        }
        else if(accountId != null && channel != '')
        {
			form.total = [SELECT count() FROM Formulary_Products_vod__c where BOT_Account__c=:accountId and BOT_Channel__c=:channel];
        	form.accountFormulary = [select Id, BOT_Channel__c, BOT_Formulary_Name__c, BOT_Product_Type__c, BOT_Account_Plan__r.Name, 
                         			BOT_Formulary_Lives__c, BOT_Sales_force_SNo__c from Formulary_Products_vod__c where 
                                    BOT_Account__c=:accountId and BOT_Channel__c=:channel order by BOT_Channel__c 
                                    LIMIT :formularyRecordToDisplay OFFSET :offset];            
        }
        /*
        Decimal firstFormularyLives = form.accountFormulary[0].BOT_Formulary_Lives__c;
        Decimal count = 0;
        Boolean isFirst = true;
        for(Formulary_Products_vod__c f : form.accountFormulary)
        {   
            if(f.BOT_Formulary_Lives__c == firstFormularyLives && isFirst == true)
            {
            	count = count + 1;
                //f.BOT_Formulary_Lives__c = 0;
                f.BOT_Sales_force_SNo__c = count;
                System.debug('BOT formulary Sno : '+f.BOT_Sales_force_SNo__c);
                isFirst = false;
            }
            if(f.BOT_Formulary_Lives__c == firstFormularyLives && isFirst == false)
            {
            	count = count + 1;
                f.BOT_Formulary_Lives__c = 0;
                f.BOT_Sales_force_SNo__c = count;
                System.debug('BOT formulary Sno : '+f.BOT_Sales_force_SNo__c);
            }
            else
            {
            	firstFormularyLives = f.BOT_Formulary_Lives__c;
               	count = 0;
                isFirst = true;
            }
        }
       	System.debug('Modified lives : '+form.accountFormulary);
		*/
        
    	// return the wrapper class instance .
        return form;
    }
    
    //To get Pharmacy Services records related to selected account
    @AuraEnabled
    public static AccountPharmacyWrapper fetchAccountPharmacy(Decimal pageNumber ,Integer pharmacyRecordToDisplay, String channel, Id accountId) {
    	Integer pageSize = pharmacyRecordToDisplay;
      	Integer offset = ((Integer)pageNumber - 1) * pageSize;
        // create a instance of wrapper class.
        AccountPharmacyWrapper pharm = new AccountPharmacyWrapper();
        // set the pageSize,Page(Number), total records and accounts List(using OFFSET)
        pharm.pageSize = pageSize;
        pharm.page = (Integer) pageNumber;
        if(accountId != null && channel == 'ALL' && channel != '')
        {
        	pharm.total = [SELECT count() FROM BOT_Pharamcy_Service__c where BOT_Account__c=:accountId];
        	pharm.accountPharmacy = [select Id, BOT_Channel__c, name, BOT_PBM_Name__c, BOT_Corporate__c, BOT_Other_Provider_Name__c 
                        			from BOT_Pharamcy_Service__c where BOT_Account__c=:accountId order by BOT_Channel__c 
                                    LIMIT :pharmacyRecordToDisplay OFFSET :offset];
        }
        else if(accountId != null && channel != '')
        {
			pharm.total = [SELECT count() FROM BOT_Pharamcy_Service__c where BOT_Account__c=:accountId and BOT_Channel__c=:channel];
        	pharm.accountPharmacy = [select Id, BOT_Channel__c, name, BOT_PBM_Name__c, BOT_Corporate__c, BOT_Other_Provider_Name__c 
                        			from BOT_Pharamcy_Service__c where BOT_Account__c=:accountId and BOT_Channel__c=:channel 
                                	order by BOT_Channel__c LIMIT :pharmacyRecordToDisplay OFFSET :offset];            
        }
    	// return the wrapper class instance .
    	return pharm;
    } 
    
    // create a wrapper class for Account Plans with @AuraEnabled Properties    
 	public class AccountPlanWrapper {
    	@AuraEnabled public Integer pageSize {get;set;}
    	@AuraEnabled public Integer page {get;set;}
    	@AuraEnabled public Integer total {get;set;}
    	@AuraEnabled public List<Account_Plan_vod__c> accountPlans {get;set;}
    }
    
    // create a wrapper class for Account Formularies with @AuraEnabled Properties
    public class AccountFormularyWrapper {
    	@AuraEnabled public Integer pageSize {get;set;}
    	@AuraEnabled public Integer page {get;set;}
    	@AuraEnabled public Integer total {get;set;}
    	@AuraEnabled public List<Formulary_Products_vod__c> accountFormulary {get;set;}        
    }
    
    // create a wrapper class for Account Formularies with @AuraEnabled Properties
    public class AccountPharmacyWrapper {
    	@AuraEnabled public Integer pageSize {get;set;}
    	@AuraEnabled public Integer page {get;set;}
    	@AuraEnabled public Integer total {get;set;}
    	@AuraEnabled public List<BOT_Pharamcy_Service__c> accountPharmacy {get;set;} 
    }
}