BusOne/src/objects/Account_Unique__c.object
<CustomObject>
    <description>To store the Master Accounts Data</description>
    <fields>
        <fullName>BOT_Account_Type__c</fullName>
        <description>To store the type of the Account like Commercial or Medicare.</description>
        <label>Account Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Entity ID</description>
        <externalId>true</externalId>
        <label>BOT_Entity_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_Level__c</fullName>
        <description>To store the Entity Level</description>
        <label>Entity Level</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_State__c</fullName>
        <description>It store the Associated state of an Entity</description>
        <label>Entity State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Accounts Unique</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Unique</pluralLabel>
    <recordTypes>
        <fullName>Commercial</fullName>
        <active>true</active>
        <description>Used to assign the commercial page layout.</description>
        <label>Commercial</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/BOT_Formularies_Unique__c.object
<CustomObject>
    <description>To sore the unique formulary values</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Account Unique.</description>
        <label>Account Name</label>
        <referenceTo>Account_Unique__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Account_Formulary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Entity ID</description>
        <label>BOT Entity ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives_Med__c</fullName>
        <description>To store the formulary lives med data</description>
        <label>Formulary Lives Med</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives__c</fullName>
        <label>Total Formulary Lives</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <description>To store formulary name</description>
        <label>Formulary Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Formularies Unique</label>
    <nameField>
        <label>Formulary Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formularies Unique</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Plan_Product__c.object
<CustomObject>
    <description>Used to store the unique plan product data.</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Account</description>
        <label>Account Name</label>
        <referenceTo>Account_Unique__c</referenceTo>
        <relationshipLabel>Plan Demographics</relationshipLabel>
        <relationshipName>BOT_Account_plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Uiqueue Entity ID</description>
        <label>BOT Entity ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Product_ID__c</fullName>
        <description>Used to store the BOT Plan Product ID</description>
        <label>Plan Product ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Lives_Rx__c</fullName>
        <description>Used to store the Plan Product Lives.</description>
        <label>Product Lives Rx</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Lives__c</fullName>
        <description>To store product lives</description>
        <label>Product Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Plan Product Unique</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_Account_Detail_Page_test.cls
@isTest(seeAllData=false)
public class BOT_Account_Detail_Page_test 
{
	public static testmethod void BOT_Account_Detail_Page()
    {
        Account_Unique__c acc = new Account_Unique__c();
        acc.name = 'Test acc 1';
        acc.BOT_Entity_ID__c = '10001';
        acc.BOT_Account_Type__c = 'Commercial';
        acc.BOT_Entity_Level__c = 'Test level 1';
        acc.BOT_Entity_State__c = 'CA';
        insert acc;
        
        Plan_Product__c plan = new Plan_Product__c();
        plan.Name = 'Test plan 1';
        plan.BOT_Entity_ID__c = '10001';
        plan.BOT_Plan_Product_ID__c = '20001';
        plan.BOT_Product_Lives__c = 500;
        plan.BOT_Product_Lives_Rx__c = 500;
		insert plan;
        List<Plan_Product__c> plans = [select Id, BOT_Account__c from Plan_Product__c limit 1];
        System.assertEquals(acc.Id, plans[0].BOT_Account__c);
        
        BOT_Formularies_Unique__c form = new BOT_Formularies_Unique__c();
        form.Name = '30001';
        form.BOT_Formulary_Name__c = 'Test formulary 1';
        form.BOT_Entity_ID__c = '10001';
       	//form.BOT_Formulary_Lives__c = 500;
        form.BOT_Formulary_Lives_Med__c = 500;
        insert form;
        List<BOT_Formularies_Unique__c> formulary = [select Id, BOT_Account__c from BOT_Formularies_Unique__c limit 1];
        System.assertEquals(acc.Id, formulary[0].BOT_Account__c);
        
        Apexpages.StandardController controller = new Apexpages.StandardController(acc);
        BOT_Account_Detail_Page_extn accUnique = new BOT_Account_Detail_Page_extn(controller);
        accUnique.initialRetrieve();
        accUnique.channelFilterRetrieve();
        accUnique.firstPlan();
        accUnique.firstFormulary();
        accUnique.selectedChannel = '--ALL--';
        accUnique.channelFilterRetrieve();
        accUnique.selectedText = 'Test';
       	accUnique.getPlansByName();
        accUnique.selectedType = 'Test';
        accUnique.getPlansByType();
        accUnique.firstPlan();
        accUnique.firstFormulary();
        accUnique.planPage = 2;
        accUnique.previousPlan();
        accUnique.formularyPage = 2;
        accUnique.previousFormulary();
        accUnique.planPage = 0;
        accUnique.nextPlan();
        accUnique.planPages = 1;
        accUnique.lastPlan();
        accUnique.formularyPage = 0;
        accUnique.nextFormulary();
        accUnique.formularyPages = 1;
        accUnique.lastFormulary();
		List<selectOption> options = accUnique.getDynamicChannels(); 
    }
}