BusOne/src/objects/Account_Plan_vod__c.object
<CustomObject>
    <description>This object stores all Account Plan header data</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account plan.</description>
        <label>Plan Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/objects/Product_vod__c.object
<CustomObject>
    <description>The Product Catalog</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup relationship to account</description>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account</relationshipLabel>
        <relationshipName>BOT_Account_Drug</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Demographics__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup relationship to Plan demographics</description>
        <label>Plan Demographics</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Product Catalog</relationshipLabel>
        <relationshipName>Plan_Demographics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Formulary_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related formulary product</description>
        <label>Formulary Product</label>
        <referenceTo>Formulary_Products_vod__c</referenceTo>
        <relationshipLabel>Drugs</relationshipLabel>
        <relationshipName>Drugs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Catalog</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_FormularyID_Update_Handler_Test.cls
/* 
Name            : BOT_FormularyID_Update_Handler_Test
Created by      : Sreenivasulu Adipudi
Created Date    : 21/Mar/2017
Description     : This test class is used to test the trigger class (BOT_FormularyID_Update_Handler) 
*/
@isTest(seeAllData=False)
public class BOT_FormularyID_Update_Handler_Test 
{
    public static testMethod void BOT_FormularyID_Update_Handler()
    {
        //inserting a record into account object
        Account acc = new Account();
        acc.name = 'Test Acc1';
        insert acc;
        //inserting a record into plan demographics object with account id
        Account_Plan_vod__c plan = new Account_Plan_vod__c();
        plan.name = 'Test Plan1';
        plan.BOT_Account__c=acc.id;
        insert plan;
        //inserting a record into formulary object with account id and plan id
        Formulary_Products_vod__c form = new Formulary_Products_vod__c();
        form.name='form1';
        form.BOT_Account__c=acc.id;
        form.BOT_Account_Plan__c=plan.id;
        insert form;
        //inserting a record into Product object with account id,plan id and formulary name (BOT formulary Id)
        Product_vod__c prod = new Product_vod__c();
        prod.Name='Drug1';
        prod.BOT_Account__c=acc.id;
        prod.BOT_Plan_Demographics__c=plan.id;
        prod.BOT_Formulary_ID__c=form.name;
        insert prod;
        //Comparing the BOT formulary Id with formulary Id in Product
        System.assertEquals('form1', prod.BOT_Formulary_ID__c);
        //System.assertEquals(form.Id, prod.Formulary_Product__c);        
    }
}