BusOne/src/objects/Account_Plan_vod__c.object
<CustomObject>
    <description>This object stores all Account Plan header data</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>It is used to Store BOT Account Id. It is used in Trigger, to update SFDC Account Id on Plan demographics. It is a hidden field.</description>
        <label>BOT_Entity_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_Update_AccId_onPlanDemographics_test.cls
@isTest(seeAllData=false)
public class BOT_Update_AccId_onPlanDemographics_test {
	public static TestMethod void BOT_Update_AccId_onPlanDemographics()
    {
        //Creating Account record
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BOT_Entity_Id__c = '1001';
        insert acc;
        //Creating Plan Demographics record
       	Account_Plan_vod__c plan = new Account_Plan_vod__c();
        plan.name = 'Test Plan1';
        plan.BOT_Entity_Id__c = '1001';
        insert plan;
        //System.assertEquals(plan.BOT_Account__c, acc.Id);
    }
}