BusOne/src/objects/Account_Plan_vod__c.object
<CustomObject>
    <description>This object stores all Account Plan header data</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to store the channel value.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>MCO Confirmed</fullName>
                </value>
                <value>
                    <fullName>PBMReport</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Product_Type__c</fullName>
        <description>Used to store the product type name.</description>
        <label>Product Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account plan.</description>
        <label>Plan Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_ChannelPBM__c</fullName>
        <description>Used to store the channel value of the PBM accounts</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to display the channel</description>
        <formula>TEXT( BOT_Account_Plan__r.BOT_Channel__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives__c</fullName>
        <description>Used to store the Formulary lives value</description>
        <label>Total Formulary Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <description>Used to store the name of the Formulary.</description>
        <label>Formulary Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Type__c</fullName>
        <description>Used to store the Product type of the associated Plan Product</description>
        <formula>BOT_Account_Plan__r.BOT_Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_FormularyLightningController.cls
public class BOT_FormularyLightningController 
{
    @AuraEnabled
    Public static List<Formulary_Products_vod__c> getAllFormularies(String formId)
    {
     	return [SELECT ID,Name,BOT_Channel__c,BOT_Product_Type__c,BOT_Account_Plan__r.Name,BOT_Formulary_Name__c,BOT_Formulary_Lives__c
                FROM Formulary_Products_vod__c
                WHERE BOT_Account__c=:formId
                ORDER BY BOT_Channel__c,Name
                LIMIT 50000
               ];   
    }
    
    @AuraEnabled
    Public static List<String> getChannels()
    {
     	String[] options = new String[]{}; 

        Schema.DescribeFieldResult fieldResult = Formulary_Products_vod__c.BOT_ChannelPBM__c.getDescribe();
        
         options.add('--All--');
        
		for(PicklistEntry f:fieldResult.getpicklistvalues())
		{
			options.add(f.getLabel());
		}
        
        return options;
    }
    
    @auraEnabled
    Public Static List<Formulary_Products_vod__c> retrieveFormularies(String accId,String channel)
    {
     	return [SELECT ID,Name,BOT_Channel__c,BOT_Product_Type__c,BOT_Account_Plan__r.Name,BOT_Formulary_Name__c,BOT_Formulary_Lives__c
                FROM Formulary_Products_vod__c
                WHERE BOT_Account__c=:accId AND BOT_Channel__c=:channel
                ORDER BY BOT_Channel__c,Name
                LIMIT 50000
               ];      
    }

}