BusOne/src/objects/Account_Territory_Loader_vod__c.object
<CustomObject>
    <description>The Account Territory Loader object is tool to modify Account territory assignments. Inserting a row into Account Territory Loader performs two operations: 1) Removes the current territory assignment for associated Account. 2) Assigns the account to the specified list of territories.</description>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>The external ID for upserting into this object.  It is recommended to use the Account Id.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Territory_To_Add_vod__c</fullName>
        <description>If a value is present, a trigger will add the value to the list of territories in Territory_vod__c. The value in the field will then be removed.</description>
        <label>Territory To Add</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_to_Drop_vod__c</fullName>
        <description>If a value is present, a trigger will remove the value from the list of territories in Territory_vod__c. The value in the field will then be removed.</description>
        <label>Territory to Drop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_vod__c</fullName>
        <description>Stores the territories associated with this account in a semicolon separated format. Salesforce.com territory rules later run on this field to actually assign territories. A leading and trailing semicolon must be contained within this field. Also, no spaces should be included in the text string. The following is an example of a valid value for this field: &quot;;TERR1;TERR2;TERR3;&quot;</description>
        <label>Territory List</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Territory Loader</label>
    <nameField>
        <displayFormat>ATL {00000000}</displayFormat>
        <label>Account Territory Loader Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Territory Loaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/VOD_ACCT_TO_TERRITORY_BEFORE_TRIG_TEST.cls
@isTest
public class VOD_ACCT_TO_TERRITORY_BEFORE_TRIG_TEST{
    static testMethod void testInsert_TerritoryIsNull_ToAddTerritoryIsNull_TerritoryToDropIsNotNull() {
         
        String objId = insertTestObject('test001Z000000CCgk0IAD',null, null, ';Territory_0;');
        Account_Territory_Loader_vod__c inserted = [SELECT Id, Territory_vod__c, Territory_To_Add_vod__c, Territory_to_Drop_vod__c 
        FROM Account_Territory_Loader_vod__c  WHERE Id= :objId];
        System.assert(inserted != null);
        System.assertEquals(inserted.Territory_to_Drop_vod__c, null);
        System.assertEquals(inserted.Territory_vod__c, null);
    }
    static testMethod void testInsert_TerritoryIsNotNull_ToAddTerritoryIsNull_TerritoryToDropIsNotNull() {
         
        String objId = insertTestObject('test001Z000000CCgk0IAD',';Territory_15;Territory_0;', null, ';Territory_0;');
        Account_Territory_Loader_vod__c inserted = [SELECT Id, Territory_vod__c, Territory_To_Add_vod__c, Territory_to_Drop_vod__c 
        FROM Account_Territory_Loader_vod__c  WHERE Id= :objId];
        System.assert(inserted != null);
        System.assertEquals(inserted.Territory_to_Drop_vod__c, null);
        System.assertEquals(inserted.Territory_vod__c, ';Territory_15;');
    }
    static testMethod void testInsert_TerritoryIsNotNull_ToAddTerritoryOverlapWithTerritoryToDrop() {
         
        String objId = insertTestObject('test1001Z000000CCgk0IAD',';Territory_15;Territory_0;',';Territory_1;', 
                                        ';Territory_1;');
        Account_Territory_Loader_vod__c inserted = [SELECT Id, Territory_vod__c, Territory_To_Add_vod__c, Territory_to_Drop_vod__c 
        FROM Account_Territory_Loader_vod__c  WHERE Id= :objId];
        System.assert(inserted != null);
        System.assertEquals(inserted.Territory_to_Drop_vod__c, null);
        System.assertEquals(inserted.Territory_vod__c, ';Territory_15;Territory_0;');
        System.assertEquals(inserted.Territory_To_Add_vod__c, null);
    }
    static testMethod void testInsert_TerritoryOverlapWithTerritoryToDrop_ToAddTerritoryIsNotNull() {
         
        String objId = insertTestObject('test2001Z000000CCgk0IAD',';Territory_15;Territory_0;',';Territory_1;', 
                                        ';Territory_0;');
        Account_Territory_Loader_vod__c inserted = [SELECT Id, Territory_vod__c, Territory_To_Add_vod__c, Territory_to_Drop_vod__c 
        FROM Account_Territory_Loader_vod__c  WHERE Id= :objId];
        System.assert(inserted != null);
        System.assertEquals(inserted.Territory_to_Drop_vod__c, null);
        System.assertEquals(inserted.Territory_vod__c, ';Territory_15;Territory_1;');
        System.assertEquals(inserted.Territory_To_Add_vod__c, null);
    }
    private static String insertTestObject(String externalId, String territory, String territoryToAdd, String territoryToDrop)
    {
        Account_Territory_Loader_vod__c obj = new Account_Territory_Loader_vod__c(
            External_ID_vod__c = externalId,
            Territory_vod__c = territory,
            Territory_To_Add_vod__c = territoryToAdd, 
            Territory_to_Drop_vod__c = territoryToDrop
        ); 
        System.Test.startTest();
        insert obj; 
        System.Test.stopTest();
        return obj.Id;
    }

}