BusOne/src/objects/Account_Plan_vod__c.object
<CustomObject>
    <description>This object stores all Account Plan header data</description>
    <label>Account Plans</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <description>Benefit Design represents a Benefit Design for a specific Managed Care (Payer) account. There may be multiple Benefit Designs for a particular account. Benefit Design Line is a child object of Benefit Design.</description>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>To store the BOT formulary ID</description>
        <label>Formulary ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <label>Benefit Design</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account plan.</description>
        <label>Plan Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/objects/Product_vod__c.object
<CustomObject>
    <description>The Product Catalog</description>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Therapeutic_Class_vod__c</fullName>
        <description>Picklist used to select the Therapeutic Class of the product such as Narcotics or Pain Relief. Therapeutic Class is controlled by the Therapeutic Area picklist.</description>
        <label>Therapeutic Class</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Therapeutic_Area_vod__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Anti-Inflammatory Medicines (NSAIDs)</fullName>
                </value>
                <value>
                    <fullName>Cox-2 Inhibitors</fullName>
                </value>
                <value>
                    <fullName>Muscle Relaxants</fullName>
                </value>
                <value>
                    <fullName>Narcotics</fullName>
                </value>
                <value>
                    <fullName>Pain Relief</fullName>
                </value>
                <value>
                    <fullName>Antianginals</fullName>
                </value>
                <value>
                    <fullName>Antiarrhythmics</fullName>
                </value>
                <value>
                    <fullName>Anticoagulants (Blood Thinners)</fullName>
                </value>
                <value>
                    <fullName>CHF Agents</fullName>
                </value>
                <value>
                    <fullName>Diuretics (Combination &quot;Water&quot; Pills)</fullName>
                </value>
                <value>
                    <fullName>Diuretics (&quot;Water&quot; Pills)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (ACE Inhibitors)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Alpha Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Angiotensin Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Beta-blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Calcium Channel Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Combination ACE Inhibitors)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Combination Angiotensin Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Combination Beta-blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Combination Calcium Channel Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Long-acting Calcium Channel Blockers)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Miscellaneous)</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure (Miscellaneous Combination Products )</fullName>
                </value>
                <value>
                    <fullName>High Cholesterol (Others)</fullName>
                </value>
                <value>
                    <fullName>High Cholesterol (Statins)</fullName>
                </value>
                <value>
                    <fullName>Vasodilators</fullName>
                </value>
                <value>
                    <fullName>Acne</fullName>
                </value>
                <value>
                    <fullName>Foot Ulcers</fullName>
                </value>
                <value>
                    <fullName>Hair Loss</fullName>
                </value>
                <value>
                    <fullName>Topical Antibiotics</fullName>
                </value>
                <value>
                    <fullName>Overactive Bladder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Catalog</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_Drug_View_Test.cls
/*
Name:BOT_Drug_View_Test
Created By :Harsha BR
Created Date:02/27/2017
Overview:Test class for the BOT_Drug_View_Extn. 
*/

@isTest(SeeAllData=True)
public class BOT_Drug_View_Test 
{
	private static testMethod void validateDrugDispaly()
    {
        //Inserting Plan Demography
        Account_Plan_vod__c objPlan = new Account_Plan_vod__c(Name = 'TestAccountName');
        insert objPlan;
        
        //Inserting Formulary Product
        Formulary_Products_vod__c objForm = new Formulary_Products_vod__c(Name = 'Test',BOT_Account_Plan__c=objPlan.Id);
        insert objForm;
        
        //Inserting Benefit Designs
        List<Benefit_Design_vod__c> lstDesigns=new List<Benefit_Design_vod__c>();
        Benefit_Design_vod__c objDesign=new Benefit_Design_vod__c(Name='sample Design');
        lstDesigns.add(objDesign);
        
        Benefit_Design_vod__c objDesign1=new Benefit_Design_vod__c(Name='sample Design1');
        lstDesigns.add(objDesign1);
        insert lstDesigns;
        
        //Inserting Drug level data
        List<Product_vod__c> lstDrugs =new List<Product_vod__c>();
        Product_vod__c objDrug=new Product_vod__c(Name='Xtandi',
                                                  BOT_Formulary_ID__c=objForm.Name,
                                                  Therapeutic_Class_vod__c='Overactive Bladder');
        lstDrugs.add(objDrug);
        
        Product_vod__c objDrug1=new Product_vod__c(Name='Mybritriq',
                                                   BOT_Formulary_ID__c=objForm.Name,
                                                   Therapeutic_Class_vod__c='Overactive Bladder');
        lstDrugs.add(objDrug1);
        insert lstDrugs;
        
        ApexPages.StandardController sc = new ApexPages.standardController(objForm);
        BOT_Drug_View_Extn controller = new BOT_Drug_View_Extn(sc);
        controller.fetchResults();
        controller.getdynamiclist();
    }
}