BusOne/src/objects/Account_Plan_vod__c.object
<CustomObject>
    <description>This object stores all Account Plan header data</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Plan_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to store the channel value.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>MCO Confirmed</fullName>
                </value>
                <value>
                    <fullName>PBMReport</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>It is used to Store BOT Account Id. It is used in Trigger, to update SFDC Account Id on Plan demographics. It is a hidden field.</description>
        <label>BOT_Entity_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Used__c</fullName>
        <label>Formulary Used</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_PBM__c</fullName>
        <label>PBM</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_ID__c</fullName>
        <description>Used to store the Account Plan ID.</description>
        <label>Plan ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Lives_Rx__c</fullName>
        <description>Used to store the Product Lives RX</description>
        <label>Product Lives Rx</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan</pluralLabel>
    <recordTypes>
        <fullName>PBM</fullName>
        <active>true</active>
        <description>Used for PBM Plan Demographies</description>
        <label>PBM</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/BOT_Coverage_Policy__c.object
<CustomObject>
    <description>To store the coverage policy details. It is having a lookup relationship with account object.</description>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>For channel selection neither commercial or medicate</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ALL</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Plan_ID__c</fullName>
        <description>It is a hidden field and it is used for internal reference purpose only</description>
        <label>Plan ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to the account object. related account Id will be populated here</description>
        <label>Plan Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Coverage Policies</relationshipLabel>
        <relationshipName>Plan_Name</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Coverage Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/BOT_Pharamcy_Service__c.object
<CustomObject>
    <description>Used to store the data related to the Pharmacy Service</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Pharamcy_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to display the channel</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Service_ID__c</fullName>
        <description>Used to store the pharmacy service ID</description>
        <label>Service ID</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Pharmacy Service</label>
    <nameField>
        <label>Pharamcy Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharmacy Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account plan.</description>
        <label>Plan Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to display the channel</description>
        <formula>TEXT( BOT_Account_Plan__r.BOT_Channel__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_Account_Summary_VF_Test.cls
/* 
Name			: BOT_Account_Summary_VF_Test
Created by		: Sreenivasulu Adipudi
Created Date	: 02/27/2017
Description		: This test class is used to test the VF Page controller class (BOT_Account_Summary_VF") 
*/
@isTest(seeAllData=false)
public class BOT_Account_Summary_VF_Test 
{
    public static testMethod void BOT_Account_Summary_Method()
    {
        Integer i;
        //inserting a record into account object
        Account acc = new Account(name='TestAccount1', BOT_Entity_Id__c = '1001');
        insert acc;
        
        //inserting a record into plan demographics object with account id
        Account_Plan_vod__c plan = new Account_Plan_vod__c(); 
        plan.BOT_Account__c = acc.id;
        plan.Name = 'Test Plan1';
        plan.BOT_Plan_ID__c = '2002';
        plan.BOT_Channel__c = 'Commercial';
        plan.BOT_Formulary_Used__c = 'Test Formulary used';
        plan.BOT_Product_Lives_Rx__c = 100;
        plan.BOT_PBM__c = 'Test PBM';
        insert plan;
        
        //inserting a record into plan formulary object with account id and plan demographics id
       	Formulary_Products_vod__c form = new Formulary_Products_vod__c();
        form.name = 'Test Formulary 1';
		form.BOT_Account__c = acc.id;
        form.BOT_Account_Plan__c = plan.id;
        form.BOT_Formulary_ID__c = '3003';
        insert form;
        
        //inserting a record into pharmacy service object with account id
        BOT_Pharamcy_Service__c pharm = new BOT_Pharamcy_Service__c();
        pharm.name = 'Test Pharm 1';
        pharm.BOT_Service_ID__c = '4004';
        pharm.BOT_Channel__c = 'Commercial';
        pharm.BOT_Account__c = acc.id;
        insert pharm;
        
        //inserting a record into coverage policy object with account id
        for(i = 1; i <= 10; i++)
        {
        	BOT_Coverage_Policy__c policy = new BOT_Coverage_Policy__c();
        	policy.name = 'Test policy '+ i;
        	policy.BOT_Channel__c = 'Commercial';
        	policy.BOT_Plan_Name__c = acc.id;
        	insert policy;
        }
        
        apexpages.StandardController controller = new apexpages.StandardController(acc);
        BOT_Account_Summary_VF ac = new BOT_Account_Summary_VF(controller);
        
        ac.initialRetrieve();
        ac.Get_Accout_Summary();
        ac.selected = '--All--';
        ac.firstPolicy();
        //ac.lastPolicy();
        //ac.previousPolicy();
        //ac.nextPolicy();
        ac.firstPlan();
        //ac.lastPlan();
        //ac.PreviousPlan();
        //ac.NextPlan();
        ac.firstForm();
        //ac.lastForm();
        //ac.NextForm();
        //ac.lastForm();
        ac.firstPhar();
        //ac.lastPhar();
        //ac.PreviousPhar();
        //ac.NextPhar();
        ac.selected = 'Commercial';
        ac.firstPolicy();
        
        // OpportunityOptions.add(new SelectOption(record.Id,record.Name))
        List<selectOption> op = new List<selectOption>();
        op.add(new selectOption('--None--','--None--'));
    }
}