BusOne/src/objects/Account_Unique__c.object
<CustomObject>
    <description>To store the Master Accounts Data</description>
    <fields>
        <fullName>BOT_Account_Type__c</fullName>
        <description>To store the type of the Account like Commercial or Medicare.</description>
        <label>Account Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Entity ID</description>
        <externalId>true</externalId>
        <label>BOT_Entity_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_Level__c</fullName>
        <description>To store the Entity Level</description>
        <label>Entity Level</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_State__c</fullName>
        <description>It store the Associated state of an Entity</description>
        <label>Entity State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Accounts Unique</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Unique</pluralLabel>
    <recordTypes>
        <fullName>Commercial</fullName>
        <active>true</active>
        <description>Used to assign the commercial page layout.</description>
        <label>Commercial</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/BOT_Formularies_Unique__c.object
<CustomObject>
    <description>To sore the unique formulary values</description>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Entity ID</description>
        <label>BOT Entity ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives_Med__c</fullName>
        <description>To store the formulary lives med data</description>
        <label>Formulary Lives Med</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives__c</fullName>
        <label>Total Formulary Lives</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <description>To store formulary name</description>
        <label>Formulary Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Formularies Unique</label>
    <nameField>
        <label>Formulary Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formularies Unique</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Plan_Formulary_JO__c.object
<CustomObject>
    <description>Junction object between plan Demographics and Plan Formulary Unique</description>
    <fields>
        <fullName>BOT_Formulary_Lives__c</fullName>
        <label>Formulary Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <label>Formulary Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Demographics_ID__c</fullName>
        <description>To store the BOT plan demographics ID</description>
        <label>BOT_Plan_Demographics_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Plan Formulary JO</label>
    <nameField>
        <label>BOT Formulary Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Formulary JOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Plan_Product__c.object
<CustomObject>
    <description>Used to store the unique plan product data.</description>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Uiqueue Entity ID</description>
        <label>BOT Entity ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Product_ID__c</fullName>
        <description>Used to store the BOT Plan Product ID</description>
        <label>Plan Product ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Lives_Rx__c</fullName>
        <description>Used to store the Plan Product Lives.</description>
        <label>Product Lives Rx</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Lives__c</fullName>
        <description>To store product lives</description>
        <label>Product Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Plan Product Unique</label>
    <nameField>
        <label>Plan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_AccountId_Update_test.cls
@isTest(seeAllData=false)
public class BOT_AccountId_Update_test 
{
	public static testmethod void BOT_AccountId_Update()
    {
        Account_Unique__c acc = new Account_Unique__c();
        acc.name = 'Test acc 1';
        acc.BOT_Entity_ID__c = '10001';
        acc.BOT_Account_Type__c = 'Commercial';
        acc.BOT_Entity_Level__c = 'Test level 1';
        acc.BOT_Entity_State__c = 'CA';
        insert acc;
        
        Plan_Product__c plan = new Plan_Product__c();
        plan.Name = 'Test plan 1';
        plan.BOT_Entity_ID__c = '10001';
        plan.BOT_Plan_Product_ID__c = '20001';
        plan.BOT_Product_Lives__c = 500;
        plan.BOT_Product_Lives_Rx__c = 500;
		insert plan;
        
        BOT_Formularies_Unique__c form = new BOT_Formularies_Unique__c();
        form.Name = '30001';
        form.BOT_Formulary_Name__c = 'Test formulary 1';
        form.BOT_Entity_ID__c = '10001';
       	//form.BOT_Formulary_Lives__c = 500;
        form.BOT_Formulary_Lives_Med__c = 500;
        insert form;
        
        Plan_Formulary_JO__c planform = new Plan_Formulary_JO__c();
        planform.Name = '30001';
        planform.BOT_Plan_Demographics_ID__c = '20001';
        insert planform;
    }
}