BusOne/src/objects/Application_Label_vod__c.object
<CustomObject>
    <description>Customized labels to be applied in offline app for special user categories, such as Medical users.</description>
    <fields>
        <fullName>Component_Name_vod__c</fullName>
        <description>Field value corresponds to the last component in Translation Workbench export. For Object type, use special values &quot;Label&quot; or &quot;LabelPlural.&quot; For Custom Field type, must be &quot;FieldLabel,&quot; &quot;HelpText,&quot; or &quot;RelatedListLabel.&quot; For all other types except Veeva Message, this is the API name of the corresponding component, e.g. button, picklist value, custom label, custom tab, layout section or validation rule.</description>
        <inlineHelpText>API name of relabeled component.</inlineHelpText>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Or_Layout_vod__c</fullName>
        <description>Field name for Custom Field and Picklist Value record types. (Note the field name of custom fields does not include the __c in the Translation Workbench export. This is the value actually entered in the UI when the field was created.)</description>
        <inlineHelpText>Field name for Custom Field and Picklist Value types - do not include __c.</inlineHelpText>
        <label>Field Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label_vod__c</fullName>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_API_Name_vod__c</fullName>
        <label>Object API Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name_vod__c</fullName>
        <description>Field for data-loading record types. Trigger on this object will read this value and find the RecordTypeID of the record type with the corresponding DeveloperName.</description>
        <inlineHelpText>DeveloperName of Record Type</inlineHelpText>
        <label>Record Type Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Application Label</label>
    <nameField>
        <displayFormat>LBL-{00000}</displayFormat>
        <label>Application Label Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Labels</pluralLabel>
    <recordTypes>
        <fullName>CustomField</fullName>
        <active>true</active>
        <label>CustomField</label>
    </recordTypes>
    <recordTypes>
        <fullName>Object_vod</fullName>
        <active>true</active>
        <label>Object_vod</label>
    </recordTypes>
    <recordTypes>
        <fullName>PicklistValue</fullName>
        <active>true</active>
        <label>PicklistValue</label>
    </recordTypes>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <label>RecordType</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Call2_vod__c.object
<CustomObject>
    <description>This object stores the main call header information. There is one call row for every account or contact on the call. A group call with 3 doctors will produce 4 call rows.</description>
    <fields>
        <fullName>Medical_Inquiry_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate a call report to a Medical Inquiry.</description>
        <label>Medical Inquiry</label>
        <referenceTo>Medical_Inquiry_vod__c</referenceTo>
        <relationshipLabel>Calls</relationshipLabel>
        <relationshipName>Calls_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call</label>
    <nameField>
        <displayFormat>C{000000000}</displayFormat>
        <label>Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Medical_Inquiry_vod__c.object
<CustomObject>
    <description>The Medical Inquiry object provides a mechanism to capture Physician based Product inquiries.  The Medical Inquiry records are typically passed to a 3rd party system for research and fulfillment via an integration.</description>
    <fields>
        <fullName>Call2_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Call is a reference field to the Call record from which the Medical Inquiry record was initiated. This reference value will be removed if the Call record is deleted.</description>
        <label>Call</label>
        <referenceTo>Call2_vod__c</referenceTo>
        <relationshipLabel>Medical Inquiries</relationshipLabel>
        <relationshipName>Medical_Inquiries_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Medical Inquiry</label>
    <nameField>
        <displayFormat>MI-{00000}</displayFormat>
        <label>Medical Inquiry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/VOD_APP_LABEL_BEFORE_INS_UPD_TEST.cls
@isTest
public class VOD_APP_LABEL_BEFORE_INS_UPD_TEST {

    /**
     * If ID is specified incoming, then Record Type Name should be populated to match.
     **/
    static testMethod void testInsertDefaultIdNoName() {
    	Application_Label_vod__c original = new Application_Label_vod__c(Object_API_Name_vod__c='Call2_vod__c',
                                                                        Component_Name_vod__c='Label',
                                                                        Label_vod__c='Interaction');
        System.Test.startTest();
       	insert original;
        System.Test.stopTest();
        
        Application_Label_vod__c saved = [SELECT Id, RecordTypeId, Record_Type_Name_vod__c 
                                          FROM Application_Label_vod__c WHERE Id=:original.Id];
        System.assert(saved.RecordTypeId != null);
        RecordType savedType = [SELECT Id, DeveloperName FROM RecordType WHERE Id=:saved.RecordTypeId];
        System.assertEquals(savedType.DeveloperName, saved.Record_Type_Name_vod__c);
    }
    
    /**
     * If RecordType ID and Name are specified, then Name should override ID.
     **/
    static testMethod void testInsertDefaultIdAndNameSpecified() {
        
    	Application_Label_vod__c original = new Application_Label_vod__c(Object_API_Name_vod__c='Call2_vod__c',
                                                                         Field_Or_Layout_vod__c='Medical_Inquiry_vod__c',
                                                                        Component_Name_vod__c='RelatedListLabel',
                                                                        Label_vod__c='Inquiry Interactions',
                                                                        Record_Type_Name_vod__c='CustomField');
        System.Test.startTest();
       	insert original;
        System.Test.stopTest();
        
        Application_Label_vod__c saved = [SELECT Id, RecordTypeId, Record_Type_Name_vod__c 
                                          FROM Application_Label_vod__c WHERE Id=:original.Id];
        System.assert(saved.RecordTypeId != null);
        RecordType savedType = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType='Application_Label_vod__c'
                                AND DeveloperName=:original.Record_Type_Name_vod__c];
        System.assertEquals(savedType.Id, saved.RecordTypeId);
    }
    
    /**
     * On Update, if ID is changed and Name is not, Name should be updated to match ID.
     **/
    static testMethod void testUpdateIdChangedNoName() {
    	Application_Label_vod__c original = new Application_Label_vod__c(Object_API_Name_vod__c='Call2_vod__c',
                                                                         Field_Or_Layout_vod__c='Medical_Inquiry_vod__c',
                                                                        Component_Name_vod__c='RelatedListLabel',
                                                                        Label_vod__c='Inquiry Interactions',
                                                                        Record_Type_Name_vod__c='PicklistValue');
       	insert original;
        
        RecordType fixType = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType='Application_Label_vod__c'
                              AND DeveloperName='CustomField'];
        System.Test.startTest();
        
        // Oops!
        Application_Label_vod__c fixed = new Application_Label_vod__c(Id=original.Id, RecordTypeId=fixType.Id);
        
        update fixed;
        
        System.Test.stopTest();
        
        Application_Label_vod__c saved = [SELECT Id, RecordTypeId, Record_Type_Name_vod__c 
                                          FROM Application_Label_vod__c WHERE Id=:original.Id];
        System.assertEquals(fixType.Id, saved.RecordTypeId);
        System.assertEquals(fixType.DeveloperName, saved.Record_Type_Name_vod__c);
    }
    
    /**
     * On update, if name is changed and ID is not, ID should be updated to match Name.
     **/
    static testMethod void testUpdateNameChangedNoId() {
    	Application_Label_vod__c original = new Application_Label_vod__c(Object_API_Name_vod__c='Call2_vod__c',
                                                                         Field_Or_Layout_vod__c='Medical_Inquiry_vod__c',
                                                                        Component_Name_vod__c='RelatedListLabel',
                                                                        Label_vod__c='Inquiry Interactions',
                                                                        Record_Type_Name_vod__c='PicklistValue');
       	insert original;

        System.Test.startTest();
        
        // Oops!
        Application_Label_vod__c fixed = new Application_Label_vod__c(Id=original.Id, Record_Type_Name_vod__c='CustomField');
        update fixed;
        
        System.Test.stopTest();

        Application_Label_vod__c saved = [SELECT Id, RecordTypeId, Record_Type_Name_vod__c 
                                          FROM Application_Label_vod__c WHERE Id=:original.Id];
        System.assert(saved.RecordTypeId != null);
        RecordType savedType = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType='Application_Label_vod__c'
                                AND DeveloperName=:fixed.Record_Type_Name_vod__c];
        System.assertEquals(saved.RecordTypeId, savedType.Id);
    }
    
    /**
     * On update, if both name and ID are changed, Name overrides and ID should be updated to match.
     **/
    static testMethod void testUpdateNameAndIdChanged() {
    	Application_Label_vod__c original = new Application_Label_vod__c(Object_API_Name_vod__c='Call2_vod__c',
                                                                         Field_Or_Layout_vod__c='Medical_Inquiry_vod__c',
                                                                        Component_Name_vod__c='RelatedListLabel',
                                                                        Label_vod__c='Inquiry Interactions',
                                                                        Record_Type_Name_vod__c='PicklistValue');
       	insert original;
        RecordType fixType = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType='Application_Label_vod__c'
                              AND DeveloperName='CustomField'];
        RecordType idType = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType='Application_Label_vod__c'
                              AND DeveloperName='Object_vod'];
        
        System.Test.startTest();
        
        // Double Oops!
        Application_Label_vod__c fixed = new Application_Label_vod__c(Id=original.Id, RecordTypeId=idType.Id,
                                                                     Record_Type_Name_vod__c=fixType.DeveloperName);
        
        update fixed;
        
        System.Test.stopTest();
        
        Application_Label_vod__c saved = [SELECT Id, RecordTypeId, Record_Type_Name_vod__c 
                                          FROM Application_Label_vod__c WHERE Id=:original.Id];
        System.assertEquals(fixType.Id, saved.RecordTypeId);
        System.assertEquals(fixType.DeveloperName, saved.Record_Type_Name_vod__c);
    }
}