BusOne/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <description>Benefit Design represents a Benefit Design for a specific Managed Care (Payer) account. There may be multiple Benefit Designs for a particular account. Benefit Design Line is a child object of Benefit Design.</description>
    <fields>
        <fullName>Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that this Benefit Design belongs to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Designs</relationshipLabel>
        <relationshipName>Account_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>To store the BOT formulary ID</description>
        <label>Formulary ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related formulary</description>
        <label>Formulary Product</label>
        <referenceTo>Formulary_Products_vod__c</referenceTo>
        <relationshipLabel>Benefit Designs</relationshipLabel>
        <relationshipName>Benefit_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related Plan Demographies</description>
        <label>Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Benefit Designs</relationshipLabel>
        <relationshipName>Benefit_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lives_vod__c</fullName>
        <description>Number of lives covered by this benefit design. This number displays in the formulary viewer.</description>
        <label>#lives</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <label>Benefit Design</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account plan.</description>
        <label>Plan Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives__c</fullName>
        <description>Used to store the Formulary lives value</description>
        <label>Total Formulary Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_BDesign_RelField_Update_Handler.cls
/*
Name        	: BOT_BDesign_RelField_Update_Handler
Created by    	: Sreenivasulu Adipudi
Created Date    : 07/MAR/2017
Overview    	: It is a trigger handler class written for BOT_BDesign_RelField_Update trigger
*/
public class BOT_BDesign_RelField_Update_Handler 
{
    public static void m1(List<Benefit_Design_vod__c>beforeInsert)
    {
        set <ID> botformid = new set<ID>();                                 //To store unique BOT formulary id values.
        List <Benefit_Design_vod__c> benefit = new List<Benefit_Design_vod__c>();   //To store the Benefit design records.
        for(Benefit_Design_vod__c ben:beforeInsert)
        {
            botformid.add(ben.BOT_Formulary_ID__c);                                 
        }
        //Retrieving the Formulary product records which is related with given benefit design records
        List <Formulary_Products_vod__c> formularyid = [select id,BOT_Account__c,BOT_Account_Plan__c,name,BOT_Formulary_Lives__c from Formulary_Products_vod__c where name in:botformid];
        //Iterating the loop to gen benefit design records
        for(Benefit_Design_vod__c ben:beforeInsert)                         
        {
            //Iterating the loop to get the related Formulary product records
            for(Formulary_Products_vod__c form:formularyid)
            {
                //Identifiying the Unique fromulary id which is related to Benefit design and populating that formulary id and lives into Benefit design record
                if(ben.Account_vod__c==form.BOT_Account__c&&ben.BOT_Product_Plan__c==form.BOT_Account_Plan__c&&ben.BOT_Formulary_ID__c==form.name)
                {
                    ben.BOT_Formulary__c=form.id;
                    ben.Lives_vod__c=form.BOT_Formulary_Lives__c;
                    benefit.add(ben);
                }
            }
        }
    }
}