BusOne/src/objects/BOT_Coverage_Policy__c.object
<CustomObject>
    <description>To store the coverage policy details. It is having a lookup relationship with account object.</description>
    <fields>
        <fullName>BOT_Conditions__c</fullName>
        <description>It is a subsection of diagnostic requirements for initial therapy</description>
        <label>Conditions</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Diagnostic_Procedure__c</fullName>
        <description>It is a subsection of diagnostic requirements for initial therapy</description>
        <label>Diagnostic Procedure</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Diagnostic_Response__c</fullName>
        <description>It is a subsection of diagnostic requirements for initial therapy</description>
        <label>Diagnostic Response</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Initial_Therapy_details__c</fullName>
        <description>It is a subsection of diagnostic requirements for initial therapy</description>
        <label>Initial Therapy details</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BOT_Monitor_for_Noneofthe_following__c</fullName>
        <description>It is a subsection of diagnostic requirements for initial therapy</description>
        <label>Monitor for / None of the following</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BOT_Requirement_s__c</fullName>
        <description>It is a sub section field of Diagnostic Requirements for Initial Therapy</description>
        <label>Requirement(s)</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Coverage Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_Diagnostic_Requirements_CP_extn.cls
public class BOT_Diagnostic_Requirements_CP_extn {
    public List<BOT_Coverage_Policy__c> coveragePolicy {get;set;}
    public BOT_Diagnostic_Requirements_CP_extn(Apexpages.StandardController controller) 
    {
    	coveragePolicy = [select Id, BOT_Initial_Therapy_details__c, BOT_Diagnostic_Procedure__c, BOT_Conditions__c, BOT_Requirement_s__c, 
                          BOT_Diagnostic_Response__c, BOT_Monitor_for_Noneofthe_following__c from BOT_Coverage_Policy__c 
                          where id =: controller.getId()];
    }
}