BusOne/src/objects/BOT_Specialty_Provider__c.object
<CustomObject>
    <description>Used to store the specialty provider details</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Specialty Providers</relationshipLabel>
        <relationshipName>Specialty_Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Specialty_ID__c</fullName>
        <description>Used to store the specialty ID</description>
        <label>Specialty ID</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Specialty Provider</label>
    <nameField>
        <label>Specialty Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialty Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/BOT_Thera_Class__c.object
<CustomObject>
    <description>Used to store the thera class records related to the Specialty Providers</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup relationship to Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Thera Classes</relationshipLabel>
        <relationshipName>TheraClass</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_SPP_ID__c</fullName>
        <description>It is used to store the BOT specialty ID. It is a reference ID for BOT.</description>
        <label>BOT SPP ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Specialty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup relationship to Specialty provider and this value will be auto-populated with a trigger.</description>
        <label>Specialty Provider</label>
        <referenceTo>BOT_Specialty_Provider__c</referenceTo>
        <relationshipLabel>Thera Classes</relationshipLabel>
        <relationshipName>Thera_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Thera Class</label>
    <nameField>
        <label>Thera Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thera Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_SPPID_In_Theraclass_Update_Handler.cls
public class BOT_SPPID_In_Theraclass_Update_Handler 
{
    public static void m1(List<BOT_Thera_Class__c>beforeList)
    {
        set<string> botsppid = new set<string>();                               //To store unique BOT SPP id values.
        List<BOT_Thera_Class__c> theraupdate = new List<BOT_Thera_Class__c>();  //To store the Thera class records with SFDC SPP id.
        for(BOT_Thera_Class__c tera:beforeList)
        {
            botsppid.add(tera.BOT_SPP_ID__c);    
        }
        //Retrieving the SPP records which is related with given Thera class records
        List<BOT_Specialty_Provider__c>sppdata=[select id,BOT_Account__c,BOT_Specialty_ID__c from BOT_Specialty_Provider__c where BOT_Specialty_ID__c in : botsppid];
        //Iterating the loop to Thera class records
        for(BOT_Thera_Class__c tera1:beforeList)
        {
            //Iterating the loop to get the related SPP records
            for(BOT_Specialty_Provider__c spp:sppdata)
            {
                //Identifiying the Unique SPP id which is related to Thera class and populating that SPP id into Thera Class record
                if(spp.BOT_Account__c==tera1.BOT_Account__c && spp.BOT_Specialty_ID__c==tera1.BOT_SPP_ID__c)
                {
                    tera1.BOT_Specialty__c=spp.id;
                    theraupdate.add(tera1);
                }
            }
        }
    }
}