BusOne/src/objects/BOT_Specialty_Provider__c.object
<CustomObject>
    <description>Used to store the specialty provider details</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Specialty Providers</relationshipLabel>
        <relationshipName>Specialty_Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_City__c</fullName>
        <description>Used to store the city name.</description>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_PBM__c</fullName>
        <description>Used to store the PBM Name</description>
        <label>PBM</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Phone__c</fullName>
        <description>Used to store the phone number.</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>BOT_SPP_Type__c</fullName>
        <description>Used to store the specialty type data.</description>
        <label>SPP Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PBM</fullName>
                </value>
                <value>
                    <fullName>Stand Alone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Specialty_ID__c</fullName>
        <description>Used to store the specialty ID</description>
        <label>Specialty ID</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_State__c</fullName>
        <description>Used to store the state name.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MP</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_website__c</fullName>
        <description>Used to store the name of the website.</description>
        <label>website</label>
        <type>Url</type>
    </fields>
    <label>Specialty Provider</label>
    <nameField>
        <label>Specialty Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialty Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/BOT_Thera_Class__c.object
<CustomObject>
    <description>Used to store the thera class records related to the Specialty Providers</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup relationship to Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Thera Classes</relationshipLabel>
        <relationshipName>TheraClass</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_SPP_ID__c</fullName>
        <description>It is used to store the BOT specialty ID. It is a reference ID for BOT.</description>
        <label>BOT SPP ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Specialty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup relationship to Specialty provider and this value will be auto-populated with a trigger.</description>
        <label>Specialty Provider</label>
        <referenceTo>BOT_Specialty_Provider__c</referenceTo>
        <relationshipLabel>Thera Classes</relationshipLabel>
        <relationshipName>Thera_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Thera_ID__c</fullName>
        <description>Used to store the BOT thera ID</description>
        <label>Thera ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Thera Class</label>
    <nameField>
        <label>Thera Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thera Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_Specialty_View_Extn.cls
/*
Name:BOT_Specialty_View_Extn
Created By :Harsha BR
Created Date:03/07/2017
Overview:Used to display the specialty provider data related to a Thera class.

Modified By: Harsha BR
Modified Date: 04/24/2017
Reason: To add Pagination
*/

public class BOT_Specialty_View_Extn 
{
    Public ID theraId{get;set;}											//To store the Thera class ID											
    Public List<BOT_Specialty_Provider__c> lstSpecialties{get;set;}		//To store the list of specialty providers
    Private static final integer list_size=10;        					//sets the page size or number of rows
    Private integer counter=0;                      					//keeps track of the offset 
    Public integer total_size{get;set;}                          		//Used to show user the total size of the list
    Private string strFilter;											//Used to store the condition to run the query
    Private string strExeQuery;											//Used to store the query to find the number of drug records
    Public Set<ID> setSpecialtyIDs{get;set;}								
    Public Boolean blnButtons{get;set;}									//To store the specialty provider IDs
    
    //Constructor
    Public BOT_Specialty_View_Extn(ApexPages.StandardController controller) 
    {
        theraId = controller.getRecord().Id;
        strFilter='';
        fetchSpecialties();
    }
    
    Public void fetchSpecialties()
    {
        ID accId;											//To store the Account ID
        String strTheraName;								//To store the Thera class Name
        Set<ID> setSpecIDs=new Set<ID>();					//To store the specialty provider IDs
        setSpecialtyIDs=new Set<ID>();
        
        List<BOT_Thera_Class__c> lstTheraclass=new List<BOT_Thera_Class__c>();
        
        //Query to retrieve the thera class details
     	List<BOT_Thera_Class__c> lstThera =[SELECT Id,Name,BOT_Account__c,BOT_Thera_ID__c,BOT_Specialty__c,BOT_SPP_ID__c
                                            FROM BOT_Thera_Class__c
                                            WHERE ID=:theraId
                                            LIMIT 1];
        accId=lstThera[0].BOT_Account__c;
        strTheraName=lstThera[0].Name;
        
        //Query to retrieve all the specialty providers related to the account
        List<BOT_Specialty_Provider__c> lstSpecProviders=[SELECT Id,BOT_Account__c,BOT_Specialty_ID__c
                                                          FROM BOT_Specialty_Provider__c
                                                          WHERE BOT_Account__c=:accId
                                                          LIMIT 50000];
        
        for(BOT_Specialty_Provider__c objSpec:lstSpecProviders)
        {
			setSpecIDs.add(objSpec.Id);   
        }
		
        //Query to retrieve all the thera class reccords
        lstTheraclass=[SELECT Id,Name,BOT_Thera_ID__c,BOT_SPP_ID__c,BOT_Specialty__c
                       FROM BOT_Thera_Class__c
                       WHERE BOT_Specialty__c IN:setSpecIDs
                       LIMIT 50000];
        
        for(BOT_Thera_Class__c objThera:lstTheraclass)
        {
         	if(objThera.Name==strTheraName)
            {
             	setSpecialtyIDs.add(objThera.BOT_Specialty__c);	   
            }
        }
        
        strFilter='Id IN:setSpecialtyIDs';
        
        String strCountQuery = 'Select Count() From BOT_Specialty_Provider__c Where ' + strFilter;
        total_size = database.Countquery(strCountQuery);
        
        if(total_size>0)
        {
            if(total_size<list_size)
            {
                blnButtons=false;
            }
            else
            {
            	 blnButtons=true;
            }
        	strExeQuery ='SELECT Id,Name,BOT_PBM__c,BOT_SPP_Type__c,BOT_Phone__c,BOT_City__c,BOT_State__c,BOT_website__c FROM BOT_Specialty_Provider__c WHERE Id IN:setSpecialtyIDs ORDER BY Name LIMIT :list_size Offset: counter';
        	fetchResults();    
        }       
    }
    
    //Used to query the Specialty Providers data
    Public void fetchResults()
    {
         lstSpecialties=database.query(strExeQuery);  
    }
    
     //This will disable the previous and first buttons
    Public Boolean getDisablePrevious() 
    { 
        if (counter>0)
        {
            return false; 
        }
        else
        {
            return true;
        }
    }
    
    //This will disable the next and last buttons
    public Boolean getDisableNext() 
    { 
        if (counter + list_size < total_size) 
        {
            return false; 
        }
        else
        {
            return true;
        }
    }
    
    //User clicked First button
    Public PageReference first()
    {
        counter = 0;
        fetchResults();
        return null;
    }
    
    //User clicked previous button
    Public PageReference Previous()
    {
        counter -= list_size;
        fetchResults();
        return null;
    }
    
    //User clicked next button
    Public PageReference Next()
    {
        counter += list_size;
        fetchResults();
        return null;
    }
    
    ///User clicked end button
    Public PageReference last()
    {
        counter = total_size - math.mod(total_size, list_size);
        if(counter==total_size)
        {
            counter-=list_size;
        }
        fetchResults();
        return null;
    }
    
    Public Integer getPageNumber() 
    {
		return counter/list_size + 1;
    }

    Public Integer getTotalPages() 
    {
       if(math.mod(total_size, list_size) > 0)
       {
			return total_size/list_size + 1;
       } 
       else
       {
			return (total_size/list_size); 
       }
   }
}