BusOne/src/objects/BOT_Specialty_Provider__c.object
<CustomObject>
    <description>Used to store the specialty provider details</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Specialty Providers</relationshipLabel>
        <relationshipName>Specialty_Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Specialty_ID__c</fullName>
        <description>Used to store the specialty ID</description>
        <label>Specialty ID</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Specialty Provider</label>
    <nameField>
        <label>Specialty Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialty Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/BOT_Thera_Class__c.object
<CustomObject>
    <description>Used to store the thera class records related to the Specialty Providers</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup relationship to Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Thera Classes</relationshipLabel>
        <relationshipName>TheraClass</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_SPP_ID__c</fullName>
        <description>It is used to store the BOT specialty ID. It is a reference ID for BOT.</description>
        <label>BOT SPP ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Thera Class</label>
    <nameField>
        <label>Thera Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thera Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_SPPID_In_TheraClass_Update_Test.cls
/* 
Name            : BOT_SPPID_In_TheraClass_Update_Test
Created by      : Sreenivasulu Adipudi
Created Date    : 06/Mar/2017
Description     : This test class is used to test the VF Page controller class (BOT_SPPID_In_Theraclass_Update_Handler) 
*/
@isTest(seeAllData=False)
public class BOT_SPPID_In_TheraClass_Update_Test 
{
    public static TestMethod void BOT_SPPID_In_TheraClass()
    {
        //inserting a record into account object
        Account acc = new Account();
        acc.name = 'Test Acc1';
        insert acc;
        //inserting a record into speciality provider object with account id
        BOT_Specialty_Provider__c spp = new BOT_Specialty_Provider__c();
        spp.BOT_Account__c=acc.id;
        spp.BOT_Specialty_ID__c='test1';
        insert spp;
        //inserting a record into Thera class object with account id and BOT speciality ID
        BOT_Thera_Class__c thera = new BOT_Thera_Class__c();
        thera.BOT_Account__c=acc.id;
        thera.BOT_SPP_ID__c=spp.BOT_Specialty_ID__c;
        thera.name='Test TheraName1';
        insert thera;
        //comparing the BOT speciality id with bot_spp_id in thera class
        System.assertEquals('test1', thera.BOT_SPP_ID__c);
    }

}