BusOne/src/objects/BOT_Formularies_Unique__c.object
<CustomObject>
    <description>To sore the unique formulary values</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Account Unique.</description>
        <label>Account Name</label>
        <referenceTo>Account_Unique__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Account_Formulary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives__c</fullName>
        <label>Total Formulary Lives</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <description>To store formulary name</description>
        <label>Formulary Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Formularies Unique</label>
    <nameField>
        <label>Formulary Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formularies Unique</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to display the channel</description>
        <formula>TEXT( BOT_Account_Plan__r.BOT_Channel__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives__c</fullName>
        <description>Used to store the Formulary lives value</description>
        <label>Total Formulary Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <description>Used to store the name of the Formulary.</description>
        <label>Formulary Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Type__c</fullName>
        <description>Used to store the Product type of the associated Plan Product</description>
        <formula>BOT_Account_Plan__r.BOT_Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Sales_force_SNo__c</fullName>
        <description>To store the Unique Sno for salesforce reference. Because there is no unique value in this object.</description>
        <label>Sales force SNo</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/objects/Plan_Formulary_JO__c.object
<CustomObject>
    <description>Junction object between plan Demographics and Plan Formulary Unique</description>
    <fields>
        <fullName>BOT_Account_Plan_Name__c</fullName>
        <label>Account Plan Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary JOs</relationshipLabel>
        <relationshipName>Plan_Formulary_JOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives__c</fullName>
        <label>Formulary Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <label>Formulary Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Formulary Product</label>
        <referenceTo>Formulary_Products_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary JOs</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Type__c</fullName>
        <label>Product type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formularies_Unique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Formularies Unique</label>
        <referenceTo>BOT_Formularies_Unique__c</referenceTo>
        <relationshipLabel>Plan Formulary JOs</relationshipLabel>
        <relationshipName>Formularies_Unique</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan Formulary JO</label>
    <nameField>
        <label>BOT Formulary Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Formulary JOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_RelFormulary_VF.cls
public class BOT_RelFormulary_VF {
    public List<BOT_Formularies_Unique__c> formulary {get;set;}
    //public List<Formulary_Products_vod__c> formulary {get;set;}
    //public List<Formulary_Products_vod__c> modifiedFormulary = new List<Formulary_Products_vod__c>();
    public Boolean temp {get;set;}
/*
    public BOT_RelFormulary_VF(ApexPages.StandardController controller)
    {
        temp = false;

        formulary = [select Id, BOT_Channel__c, name, BOT_Formulary_Lives__c, (select Id, BOT_Formulary_Product__c, BOT_Channel__c, BOT_Formulary_Name__c, BOT_Product_Type__c, 
                     BOT_Account_Plan_Name__c from Formularies_Unique__r) from BOT_Formularies_Unique__c LIMIT 50];
        System.debug('formulary :'+formulary);
        if(formulary.size()>0 && formulary != null)
        {
            temp = true;            
        }

        formulary = [select Id, name, BOT_Account__c, BOT_Channel__c, BOT_Formulary_Name__c, BOT_Product_Type__c, BOT_Formulary_Lives__c, BOT_Sales_force_SNo__c 
                     from Formulary_Products_vod__c order by BOT_Account__c LIMIT 500];
        Formulary_Products_vod__c oneFormulary = formulary[0];
        Integer count = 0;
        for(Formulary_Products_vod__c form : formulary)
        {
            if(oneFormulary.BOT_Account__c == form.BOT_Account__c && oneFormulary.Name == form.Name)
            {
                count = count + 1;
                form.BOT_Sales_force_SNo__c = 0;
                System.debug('BOT_Sales_force_SNo__c : '+form.BOT_Sales_force_SNo__c);
            }
            else if(oneFormulary.BOT_Account__c != form.BOT_Account__c && oneFormulary.Name != form.Name)
            {
                oneFormulary.BOT_Sales_force_SNo__c = count;
                modifiedFormulary.add(oneFormulary);
                oneFormulary = form;
                count = 1;
            }
        }
        formulary.clear();
        formulary.addAll(modifiedFormulary);
        

    }
            */
}