BusOne/src/objects/Business_Event_Target_vod__c.object
<CustomObject>
    <description>Account targets of Business Event</description>
    <fields>
        <fullName>Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Event Targets</relationshipLabel>
        <relationshipName>Business_Event_Targets_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Event_vod__c</fullName>
        <description>The parent object that this detail information belongs to</description>
        <label>Business Event</label>
        <referenceTo>Business_Event_vod__c</referenceTo>
        <relationshipLabel>Business Event Targets</relationshipLabel>
        <relationshipName>Business_Event_Targets_vod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Business Event Target</label>
    <nameField>
        <displayFormat>BET{000000000}</displayFormat>
        <label>Business Event Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Event Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne/src/objects/Business_Event_vod__c.object
<CustomObject>
    <description>Top level object that holds various regulation events.</description>
    <label>Business Event</label>
    <nameField>
        <label>Business Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Call2_vod__c.object
<CustomObject>
    <description>This object stores the main call header information. There is one call row for every account or contact on the call. A group call with 3 doctors will produce 4 call rows.</description>
    <fields>
        <fullName>Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the account that the call is associated with.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Calls (Account)</relationshipLabel>
        <relationshipName>Call2_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call</label>
    <nameField>
        <displayFormat>C{000000000}</displayFormat>
        <label>Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Call_Objective_vod__c.object
<CustomObject>
    <description>Call Objective can be accessed through Call Report</description>
    <fields>
        <fullName>Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that this tasks belongs to</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Objectives</relationshipLabel>
        <relationshipName>Call_Objectives_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Event_Target_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Event Target</description>
        <label>Business Event Target</label>
        <referenceTo>Business_Event_Target_vod__c</referenceTo>
        <relationshipLabel>Call Objectives</relationshipLabel>
        <relationshipName>Call_Objectives_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the event this task belongs to</description>
        <label>Business Event</label>
        <referenceTo>Business_Event_vod__c</referenceTo>
        <relationshipLabel>Call Objectives</relationshipLabel>
        <relationshipName>Call_Objectives_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call2_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the call that this task belongs to</description>
        <label>Call</label>
        <referenceTo>Call2_vod__c</referenceTo>
        <relationshipLabel>Call Objectives</relationshipLabel>
        <relationshipName>Call_Objectives_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_Flag_vod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If MR finish this task, this flag is true</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_vod__c</fullName>
        <description>The date time of plan or activity date for task</description>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>From_Date_vod__c</fullName>
        <description>The date range for each actions</description>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name_vod__c</fullName>
        <description>The Name_vod field is used by iRep to display the name of the call objective in the call objectives list view. This field is also searchable in iRep.</description>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Objective_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a parent call objective. Used for grouping recurring call objectives. Automatically populated.</description>
        <label>Parent Objective</label>
        <referenceTo>Call_Objective_vod__c</referenceTo>
        <relationshipLabel>Call Objectives</relationshipLabel>
        <relationshipName>Call_Objectives_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_vod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this checkbox is checked, the call objective is recurring. It will repeatedly show on the call report until the To date has been reached, It can be completed multiple times. Each time it is completed, a new call objective record is created.</description>
        <label>Recurring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Date_vod__c</fullName>
        <description>The date range for each actions</description>
        <label>To</label>
        <type>Date</type>
    </fields>
    <label>Call Objective</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/VOD_CALL_OBJECTIVE_UPDATE_TRIG_TEST.cls
@isTest
public class VOD_CALL_OBJECTIVE_UPDATE_TRIG_TEST {
    static testMethod void testupdate_Completed_Call_Objective_With_FlipRecurringToTrue_ShouldFail() {
        
       System.Test.startTest();
       String objId = insertTestObject(false,null);
       System.Test.stopTest();
 
        Call_Objective_vod__c inserted = [SELECT Call2_vod__c,Completed_Flag_vod__c,Date_vod__c,From_Date_vod__c,Id,Name_vod__c,
                                   RecordTypeId,Recurring_vod__c,To_Date_vod__c FROM Call_Objective_vod__c 
                                                    WHERE Id= :objId LIMIT 1];
        try {
            objId = updateTestObject(inserted,null, true,true);
            Call_Objective_vod__c updated = [SELECT Call2_vod__c,Completed_Flag_vod__c,Date_vod__c,From_Date_vod__c,Id,Name_vod__c,
                                       RecordTypeId,Recurring_vod__c,To_Date_vod__c FROM Call_Objective_vod__c 
                                                        WHERE Id= :objId LIMIT 1];
        }
        catch(Exception e)
        {
            System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
    }
    static testMethod void testupdate_Called_Call_Objective_With_FlipRecurringToTrue_ShouldFail() {
       system.Test.startTest();
       String objId = insertTestObject(false,null);
       System.Test.stopTest();
 
        Call_Objective_vod__c inserted = [SELECT Call2_vod__c,Completed_Flag_vod__c,Date_vod__c,From_Date_vod__c,Id,Name_vod__c,
                                   RecordTypeId,Recurring_vod__c,To_Date_vod__c FROM Call_Objective_vod__c 
                                                    WHERE Id= :objId LIMIT 1];
        try {
            objId = updateTestObject(inserted,'a04Z0000009KLFOIA4', false,true);
            Call_Objective_vod__c updated = [SELECT Call2_vod__c,Completed_Flag_vod__c,Date_vod__c,From_Date_vod__c,Id,Name_vod__c,
                                       RecordTypeId,Recurring_vod__c,To_Date_vod__c FROM Call_Objective_vod__c 
                                                        WHERE Id= :objId LIMIT 1];
        }
        catch(Exception e)
        {
            System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
    }
    static testMethod void testupdate_Childed_Call_Objective_With_FlipRecurringToFalse_ShouldFail() {
       system.Test.startTest();
       String objId = insertTestObject(true,null);
       String objChildId = insertTestObject(true,objId);
       System.Test.stopTest();
 
        Call_Objective_vod__c inserted = [SELECT Call2_vod__c,Completed_Flag_vod__c,Date_vod__c,From_Date_vod__c,Id,Name_vod__c,
                                   RecordTypeId,Recurring_vod__c,To_Date_vod__c FROM Call_Objective_vod__c 
                                                    WHERE Id= :objId LIMIT 1];
        try {
            objId = updateTestObject(inserted,null, false,false);
            Call_Objective_vod__c updated = [SELECT Call2_vod__c,Completed_Flag_vod__c,Date_vod__c,From_Date_vod__c,Id,Name_vod__c,
                                       RecordTypeId,Recurring_vod__c,To_Date_vod__c FROM Call_Objective_vod__c 
                                                        WHERE Id= :objId LIMIT 1];
        }
        catch(Exception e)
        {
            System.Assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
    }
    static testMethod void testupdate_NoChilded_Call_Objective_With_FlipRecurringToFalse_ShouldPass() {
       system.Test.startTest();
       String objId = insertTestObject(true,null);
       //String objChildId = insertTestObject(true,objId);
       System.Test.stopTest();
 
        Call_Objective_vod__c inserted = [SELECT Call2_vod__c,Completed_Flag_vod__c,Date_vod__c,From_Date_vod__c,Id,Name_vod__c,
                                   RecordTypeId,Recurring_vod__c,To_Date_vod__c FROM Call_Objective_vod__c 
                                                    WHERE Id= :objId LIMIT 1];
        
        objId = updateTestObject(inserted,null, false,false);
        Call_Objective_vod__c updated = [SELECT Call2_vod__c,Completed_Flag_vod__c,Date_vod__c,From_Date_vod__c,Id,Name_vod__c,
                                         RecordTypeId,Recurring_vod__c,To_Date_vod__c FROM Call_Objective_vod__c 
                                         WHERE Id= :objId LIMIT 1];
        System.assertEquals(false, updated.Recurring_vod__c);
    }
    private static String insertTestObject(boolean Recurring, String parentId){
       Call_Objective_vod__c obj = new Call_Objective_vod__c(
            Business_Event_vod__c = 'a1kZ0000000eanUIAQ' ,
            Business_Event_Target_vod__c='a1jZ0000001ValyIAC',
            Account_vod__c = '001Z000000CEglvIAD',
            Name_vod__c = 'test',
            Recurring_vod__c = Recurring,
            RecordTypeId='012A0000000k5siIAA',
            Date_vod__c = Datetime.now()
        ); 
        if(parentId != null){
            obj.Parent_Objective_vod__c = parentId;
        }
        insert obj; 
        return obj.Id; 
    } 
    private static String updateTestObject(Call_Objective_vod__c updateObj,String Call, boolean Completed,boolean Recurring){
       Call_Objective_vod__c obj = updateObj;
       updateObj.Completed_Flag_vod__c = Completed;
       updateObj.Call2_vod__c = Call;
       updateObj.Recurring_vod__c = Recurring;
        
        update obj; 
        return obj.Id; 
    }
}