BusOne/src/objects/Country_vod__c.object
<CustomObject>
    <description>Used for configuration and record tagging</description>
    <fields>
        <fullName>Country_Name_vod__c</fullName>
        <description>Translatable country name.
Includes all values in the ISO standard. http://en.wikipedia.org/wiki/ISO_3166-1</description>
        <label>Country Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AF</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>AI</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AQ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>AW</fullName>
                </value>
                <value>
                    <fullName>AX</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BF</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BJ</fullName>
                </value>
                <value>
                    <fullName>BL</fullName>
                </value>
                <value>
                    <fullName>BM</fullName>
                </value>
                <value>
                    <fullName>BN</fullName>
                </value>
                <value>
                    <fullName>BO</fullName>
                </value>
                <value>
                    <fullName>BQ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/EM_Attendee_vod__c.object
<CustomObject>
    <description>Attendees at events for Veeva Events Management</description>
    <fields>
        <fullName>End_Time_vod__c</fullName>
        <description>End time of the event</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time_vod__c</fullName>
        <description>Start time of the event</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>EA-{0000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BusOne/src/objects/EM_Event_Configuration_Country_vod__c.object
<CustomObject>
    <description>Linking table between Event Configuration and Country</description>
    <fields>
        <fullName>Country_vod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The country the event configuration is for.</description>
        <label>Country</label>
        <referenceTo>Country_vod__c</referenceTo>
        <relationshipLabel>Event Configuration Countries</relationshipLabel>
        <relationshipName>EM_Event_Configuration_Country_vod</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Configuration_vod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The event configuration used by the selected country. An event configuration defines an event type and a time period the configuration is valid for.</description>
        <label>Event Configuration</label>
        <referenceTo>EM_Event_Configuration_vod__c</referenceTo>
        <relationshipLabel>Event Configuration Countries</relationshipLabel>
        <relationshipName>Event_Configuration_Country_vod</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Event Configuration Country</label>
    <nameField>
        <displayFormat>ECC-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Configuration Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/EM_Event_Rule_vod__c.object
<CustomObject>
    <description>Used to store rules for a particular event type. Used by Veeva Event Management.</description>
    <fields>
        <fullName>Child_Event_Record_Type_vod__c</fullName>
        <description>Defines which record type is used for an event configuration</description>
        <label>Child Event Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Override_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used if an event rule only applies to one specific country within the Event Configuration set.</description>
        <label>Country Override</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EM_Event_Configuration_Country_vod__c.Event_Configuration_vod__c</field>
                <operation>equals</operation>
                <valueField>$Source.Event_Configuration_vod__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EM_Event_Configuration_Country_vod__c</referenceTo>
        <relationshipLabel>Event Rules</relationshipLabel>
        <relationshipName>Event_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Configuration_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The event configuration that the event rule is applied to.</description>
        <label>Event Configuration</label>
        <referenceTo>EM_Event_Configuration_vod__c</referenceTo>
        <relationshipLabel>Event Rules</relationshipLabel>
        <relationshipName>Event_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Rule</label>
    <nameField>
        <displayFormat>ER-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Rules</pluralLabel>
    <recordTypes>
        <fullName>Child_Event_Settings_vod</fullName>
        <active>true</active>
        <description>Configures child events that are associated to an event configuration</description>
        <label>Child_Event_Settings_vod</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/EM_Event_Speaker_vod__c.object
<CustomObject>
    <description>Speaker at an event for Veeva Event Management.</description>
    <fields>
        <fullName>End_Time_vod__c</fullName>
        <description>End time of the event</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time_vod__c</fullName>
        <description>Start time of the event</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event Speaker</label>
    <nameField>
        <displayFormat>ESP-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BusOne/src/objects/EM_Event_vod__c.object
<CustomObject>
    <description>Events object for Veeva Events Management</description>
    <fields>
        <fullName>Country_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where an event takes place. Used to define event-level rules.</description>
        <label>Country</label>
        <referenceTo>Country_vod__c</referenceTo>
        <relationshipName>EM_Event_Country_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time_vod__c</fullName>
        <description>End time of the event.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Configuration_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System field used for performance purposes. This field should not be placed on the page layout.</description>
        <label>Event Configuration</label>
        <referenceTo>EM_Event_Configuration_vod__c</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links events together in a series.</description>
        <label>Parent Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipName>EM_Event_Parent_Event_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time_vod__c</fullName>
        <description>Start time of the event.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event1</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events3</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BusOne/src/objects/Event_Attendee_vod__c.object
<CustomObject>
    <description>This is a child object of Medical Event. One row represents a entity (Account, Contact, User) who has been invited to attended to the Medical Event. The Attendee_vod field is updated by a trigger to insure it always matches the name field of the account, contact, or user on create/update.</description>
    <fields>
        <fullName>EM_Attendee_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used by the system. It must be visible to users of Veeva Event Management.</description>
        <label>Attendee</label>
        <referenceTo>EM_Attendee_vod__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EM_Event_Speaker_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used by the system. It must be visible to users of Veeva Event Management.</description>
        <label>Event Speaker</label>
        <referenceTo>EM_Event_Speaker_vod__c</referenceTo>
        <relationshipLabel>Event Attendees(Event Speaker)</relationshipLabel>
        <relationshipName>Event_Attendees_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Medical_Event_vod__c</fullName>
        <description>The Medical Event that the Account, Contact, or User is attending.</description>
        <label>Medical Event</label>
        <referenceTo>Medical_Event_vod__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendee_vod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>A{000000000}</displayFormat>
        <label>Attendee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne/src/objects/Medical_Event_vod__c.object
<CustomObject>
    <description>This object is used to store medical events. It is not related to the base salesforce.com event (calendar event) object. It has one standard child (event attendees), but custom objects can be added as children to track different attributes of medical events. Medical Event is a top level object with its own security and is referred to in the call reporting functionality.</description>
    <fields>
        <fullName>Country_Name_vod__c</fullName>
        <description>Country of Medical Event location</description>
        <label>Country Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EM_Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used by the system. It must be visible to users of Veeva Event Management.</description>
        <label>Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>Medical Events</relationshipLabel>
        <relationshipName>Medical_Events_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time_vod__c</fullName>
        <description>End time of the event.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time_vod__c</fullName>
        <description>Start time of the event.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Medical Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/objects/Preferences_vod__c.object
<CustomObject>
    <description>A set of preferences for users or profiles.</description>
    <fields>
        <fullName>Event_Management_User_vod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to indicate if a user has Veeva Event Management. To turn on Event Management, the user must have read permission to this field. The checkbox does not need to be checked.</description>
        <label>Event Management User</label>
        <type>Checkbox</type>
    </fields>
    <label>Preferences</label>
    <nameField>
        <label>Preferences Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/EMRedirectController.cls
public with sharing class EMRedirectController {
    boolean isStub = false;
    boolean isEMUser = false;
    ApexPages.StandardController controller;
    String attendeeStubId;
    String eventStubId;
    String startTime;
    String endTime;
    String country;
    String retURL;
    String parentId;
    String recordTypeId;
	String childEventRuleRecordTypeId;

    public EMRedirectController(ApexPages.StandardController controller) {
        this.controller = controller;
        isEmUser = Schema.SObjectType.Preferences_vod__c.fields.Event_Management_User_vod__c.isAccessible();
        retURL = ApexPages.currentPage().getParameters().get('retURL');
        recordTypeId= ApexPages.currentPage().getParameters().get('RecordType');
        if(isEMUser) {
            sObject record = controller.getRecord();
        	if(isAttendee()) {
                if(record.get('EM_Attendee_vod__c') != null) {
                    isStub = true;
                    attendeeStubId = (String)record.get('EM_Attendee_vod__c');
                } else if (record.get('EM_Event_Speaker_vod__c') != null) {
                    isStub = true;
                    attendeeStubId = (String)record.get('EM_Event_Speaker_vod__c');
                }
            } else if (isMedicalEvent()) {
                if(record.get('EM_Event_vod__c') != null) {
                    isStub = true;
                    eventStubId = (String)record.get('EM_Event_vod__c');
                }
            } else if(isEMEvent()) {
                DateTime tempDateTime;
                if(record.get('Start_Time_vod__c') != null) {
                    tempDateTime = (DateTime)record.get('Start_Time_vod__c');
                    startTime = tempDateTime.format();
                }
                if(record.get('End_Time_vod__c') != null) {
                    tempDateTime = (DateTime)record.get('End_Time_vod__c');
                    endTime = tempDateTime.format();
                }
                if(record.get('Id') != null) {
                    parentId = (String)record.get('Id');
                }
                if(record.get('Country_vod__c') != null) {
                    country = (String)record.get('Country_vod__c');
                }
            }
        }
    }

    private boolean isAttendee() {
        return controller.getRecord().getSObjectType().getDescribe().getName() == 'Event_Attendee_vod__c';
    }

    private boolean isMedicalEvent() {
    	return controller.getRecord().getSObjectType().getDescribe().getName() == 'Medical_Event_vod__c';
    }

    private boolean isEMEvent() {
        return controller.getRecord().getSObjectType().getDescribe().getName() == 'EM_Event_vod__c';
    }

    public PageReference redirectEdit() {
        String objectId = controller.getId();

        if(objectId == null) {
            Schema.DescribeSObjectResult describe = controller.getRecord().getSObjectType().getDescribe();
            objectId = describe.getKeyPrefix();
        }

        if(!isEMUser) {
            if(recordTypeId != null) {
            	return new PageReference('/' + objectId + '/e?retURL=' + retURL +'&nooverride=1&RecordType=' + recordTypeId);
            } else {
                return new PageReference('/' + objectId + '/e?retURL=' + retURL +'&nooverride=1');
            }
        }

        if(isStub) {
            if(isAttendee()) {
                return new PageReference('/' + attendeeStubId + '/e?retURL=' + retURL);
            } else if (isMedicalEvent()) {
                return new PageReference('/' + eventStubId + '/e?retURL=' + retURL);
            }
        }

        if(recordTypeId != null) {
            return new PageReference('/' + objectId + '/e?retURL=' + retURL +'&nooverride=1&RecordType=' + recordTypeId);
        } else {
            return new PageReference('/' + objectId + '/e?retURL=' + retURL +'&nooverride=1');
        }
    }

    public PageReference redirectView() {
        if(!isEMUser) {
            new PageReference('/' + controller.getId() + '?retURL=' + retURL + '&nooverride=1');
        }
        if(isStub) {
            if(isAttendee()) {
                return new PageReference('/' + attendeeStubId);
            } else if (isMedicalEvent()) {
                return new PageReference('/' + eventStubId);
            }
        }
        return new PageReference('/' + controller.getId() + '?retURL=' + retURL + '&nooverride=1');
    }

    public PageReference redirectNewEventChild() {
        String eventObjectId = VOD_RedirectUtil.getObjectDurableId('EM_Event_vod');
        String childPageUrl = '/setup/ui/recordtypeselect.jsp?ent=' + EncodingUtil.urlEncode(eventObjectId.substring(0,15), 'UTF-8');
        boolean skipRTSelector = false;

        //--EM Child Event Settings Rule--
        try {
            if (childEventRuleRecordTypeId == null) childEventRuleRecordTypeId = [SELECT Id FROM RecordType WHERE sObjectType ='EM_Event_Rule_vod__c' AND DeveloperName='Child_Event_Settings_vod'].Id;

            //find the event rule that is in the event configuration associated with the parent event,
            //is the child event rule record type, and the country_override.country is equal the to parent event's country
            EM_Event_vod__c parentEMConfig = [SELECT Event_Configuration_vod__c FROM EM_Event_vod__c WHERE Id = :parentId];
        	EM_Event_Configuration_Country_vod__c parentEventConfigCountry = [SELECT Country_vod__c FROM EM_Event_Configuration_Country_vod__c WHERE EM_Event_Configuration_Country_vod__c.Country_vod__c =: country AND EM_Event_Configuration_Country_vod__c.Event_Configuration_vod__c = :parentEMConfig.Event_Configuration_vod__c];

            List<EM_Event_Rule_vod__c> childEventRuleWithCOList = [SELECT Child_Event_Record_Type_vod__c
                                                        FROM EM_Event_Rule_vod__c
                                                        WHERE Event_Configuration_vod__c = :parentEMConfig.Event_Configuration_vod__c
                                                        	AND EM_Event_Rule_vod__c.RecordTypeId = :childEventRuleRecordTypeId
                                                         	AND EM_Event_Rule_vod__c.Country_Override_vod__c = :parentEventConfigCountry.Id];
            if (childEventRuleWithCOList.size() > 0) {
                //this should only ever have 1 record, since we use the unique key of event config and country override, unless the trigger is bugged and allows duplicate event rules
                EM_Event_Rule_vod__c childEventRuleWithCO = childEventRuleWithCOList.get(0);
                if (childEventRuleWithCO.Child_Event_Record_Type_vod__c != null) {
                    childPageUrl = '/apex/EM_Event_New_vod?RecordType='+ [SELECT Id FROM RecordType WHERE sObjectType = 'EM_Event_vod__c' and DeveloperName = :childEventRuleWithCO.Child_Event_Record_Type_vod__c].Id;
                    skipRTSelector = true;
                }
            } else {
                //finds the event rule that is in the event configuration associated with the parent event,
                //is the child event rule record type, and country_override field is blank
                //if the below query returns 0 results, thats fine, we catch the exception and carry on since no rule will be applied
                EM_Event_Rule_vod__c childEventRuleWithoutCO = [SELECT Child_Event_Record_Type_vod__c
                                                            FROM EM_Event_Rule_vod__c
                                                            WHERE Event_Configuration_vod__c = :parentEMConfig.Event_Configuration_vod__c
                                                                AND EM_Event_Rule_vod__c.RecordTypeId = :childEventRuleRecordTypeId
                                                                AND EM_Event_Rule_vod__c.Country_Override_vod__c = null ];

                if (childEventRuleWithoutCO.Child_Event_Record_Type_vod__c != null ) {
                    childPageUrl = '/apex/EM_Event_New_vod?RecordType='+ [SELECT Id FROM RecordType WHERE sObjectType = 'EM_Event_vod__c' and DeveloperName = :childEventRuleWithoutCO.Child_Event_Record_Type_vod__c].Id;
                	skipRTSelector = true;
                }
            }
        } catch (Exception e) {
            //catch the 0 records exception
        }


        String eventKeyPrefix = controller.getRecord().getSObjectType().getDescribe().getKeyPrefix();
        childPageUrl += '&save_new_url=/'+ eventKeyPrefix + '/e?retURL=' + EncodingUtil.urlEncode('/' + controller.getId(), 'UTF-8');
        if(startTime != null) {
            childPageUrl += '&Start_Time_vod__c=' + startTime;
        }
        if(parentId != null) {
            childPageUrl += '&Parent_Event_vod__c=' + parentId;
        }
        if(country != null) {
            Country_vod__c countryObj = [SELECT Country_Name_vod__c FROM Country_vod__c WHERE Id =: country];

            childPageUrl += '&parentCountry=' + countryObj.Country_Name_vod__c;
        }
        if(endTime != null) {
            childPageUrl += '&End_Time_vod__c=' + endTime;
        }
        if (skipRTSelector) {
            childPageUrl += '#/event-wizard';
        }


        System.debug(childPageUrl);
        PageReference newChildPage = new PageReference(childPageUrl);
        newChildPage.setRedirect(true);
        return newChildPage;
    }
}