BusOne/src/objects/EM_Budget_vod__c.object
<CustomObject>
    <description>Used to store a budget hierarchy.</description>
    <fields>
        <fullName>Actual_Expenses_vod__c</fullName>
        <description>Amount of expenses already distributed from this budget.</description>
        <label>Actual Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Committed_Expenses_vod__c</fullName>
        <description>Amount of committed funds that will be used for events, not including non-committed estimates or paid expenses</description>
        <label>Committed Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Expenses_vod__c</fullName>
        <description>Amount of estimated funds that will be used for events, not including committed or paid expenses.</description>
        <label>Estimated Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Parent_Budget_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship to a parent budget.</description>
        <label>Parent Budget</label>
        <referenceTo>EM_Budget_vod__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Parent_Budget_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/VOD_EVENT_TRIG.cls
public class VOD_EVENT_TRIG {
    public static void rollUptoBudget(Decimal committed, Decimal estimated, Id budgetId) {
        if(budgetId != null && (committed != 0 || estimated != 0)) {
            EM_Budget_vod__c budget = [Select Actual_Expenses_vod__c,
                                              Committed_Expenses_vod__c,
                                              Estimated_Expenses_vod__c,
                                              Parent_Budget_vod__c
                                              FROM EM_Budget_vod__c
                                              WHERE Id = :budgetId]; 
            if(budget != null) {
                if(budget.Committed_Expenses_vod__c == null) {
                    budget.Committed_Expenses_vod__c = committed;
                } else {
                	budget.Committed_Expenses_vod__c += committed;    
                }
                
                if(budget.Estimated_Expenses_vod__c == null) {
                    budget.Estimated_Expenses_vod__c = estimated;
                } else {
                	budget.Estimated_Expenses_vod__c += estimated;    
                }
				update budget;
                if(budget.Parent_Budget_vod__c != null) {
                	rolluptoBudget(committed, estimated, budget.Parent_Budget_vod__c);    
                }                                                
            }          
        }
    }
}