BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account plan.</description>
        <label>Plan Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <description>Used to store the name of the Formulary.</description>
        <label>Formulary Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/objects/Product_vod__c.object
<CustomObject>
    <description>The Product Catalog</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup relationship to account</description>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account</relationshipLabel>
        <relationshipName>BOT_Account_Drug</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_ID__c</fullName>
        <description>Used to store the Formulary ID</description>
        <label>Formulary ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Demographics__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup relationship to Plan demographics</description>
        <label>Plan Demographics</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Product Catalog</relationshipLabel>
        <relationshipName>Plan_Demographics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Formulary_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related formulary product</description>
        <label>Formulary Product</label>
        <referenceTo>Formulary_Products_vod__c</referenceTo>
        <relationshipLabel>Drugs</relationshipLabel>
        <relationshipName>Drugs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Catalog</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_FormularyID_Update_Handler.cls
/*
Name    	: BOT_FormularyID_Update_Handler
Created by  : Sreenivasulu Adipudi
Created date: 21-MAR-2017
Description	: It is a helper class for BOT_FormularyID_Update_On_Product trigger
*/
public class BOT_FormularyID_Update_Handler 
{
    public static void m1(List<Product_vod__c>beforeinsert)
    {
        set<String> botformularyid = new set<String>();	//To store the products object unique formulary IDs
        //Iterating and getting the unique formulary IDs
        for(Product_vod__c prod : beforeinsert)
        {
            botformularyid.add(prod.BOT_Formulary_ID__c);
        }
        //Getting formulary records which is related to the given formulary IDs
        List<Formulary_Products_vod__c> selectedformularyid = [select ID,Name,BOT_Account__c,BOT_Account_Plan__c,BOT_Formulary_Name__c from Formulary_Products_vod__c where Name in : botformularyid];
        //Iterating Product object records
        for(Product_vod__c prod: beforeinsert)
        {
            //Iterating the formulary records
            for(Formulary_Products_vod__c formulary : selectedformularyid)
            {
                //Comparing Product records with formulary records
                if(formulary.BOT_Account__c==prod.BOT_Account__c&&formulary.BOT_Account_Plan__c==prod.BOT_Plan_Demographics__c&&formulary.Name == prod.BOT_Formulary_ID__c)
                {
                    //populating SFDC formulary ID in Formulary_Product__c field of Product object
                    prod.Formulary_Product__c = formulary.id;                                                       
                }
            }
        }
    }
}