BusOne/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the related account plan.</description>
        <label>Plan Product Name</label>
        <referenceTo>Account_Plan_vod__c</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Formulary</relationshipLabel>
        <relationshipName>Formulary_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>Used to display the channel</description>
        <formula>TEXT( BOT_Account_Plan__r.BOT_Channel__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Lives__c</fullName>
        <description>Used to store the Formulary lives value</description>
        <label>Total Formulary Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <description>Used to store the name of the Formulary.</description>
        <label>Formulary Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Type__c</fullName>
        <description>Used to store the Product type of the associated Plan Product</description>
        <formula>BOT_Account_Plan__r.BOT_Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Formulary ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne/src/classes/BOT_RelFormulary_On_Account_VF.cls
/*
Name        : BOT_RelFormulary_On_Account_VF
Created by    : Sreenivasulu Adipudi
Created Date    : 08/MAR/2017
Overview    : It is a controller class for BOT_RelFormulary_On_Account VF Page
*/
public with sharing class BOT_RelFormulary_On_Account_VF 
{
    public Account accountId {get;set;}
    Public set<String> channel=new set<String>();
    public List<Formulary_Products_vod__c> allchannel = new List<Formulary_Products_vod__c>();
    Public List<Formulary_Products_vod__c> allformulary {get;set;}
    public List<Formulary_Products_vod__c> selectedformulary = new List<Formulary_Products_vod__c>();
    public BOT_RelFormulary_On_Account_VF(Apexpages.StandardController controller)
    {
        this.accountId=(Account)controller.getRecord();
        allchannel = [select ID,BOT_Account__c,BOT_Channel__c from Formulary_Products_vod__c where BOT_Account__c =: accountId.id];
        for(Formulary_Products_vod__c form:allchannel)
        {
            channel.add(form.BOT_Channel__c);
        }
        allformulary=[select ID,Name,BOT_Channel__c,BOT_Product_Type__c,BOT_Account_Plan__c,BOT_Formulary_Name__c,BOT_Formulary_Lives__c from Formulary_Products_vod__c where BOT_Channel__c =: channel and BOT_Account__c =: accountId.id];
     }
    
}