BusOne/src/objects/Mobile_Device_vod__c.object
<CustomObject>
    <description>Mobile devices associated with the User</description>
    <fields>
        <fullName>Active_vod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the mobile device is active</description>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User the mobile device is associated with</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Mobile_Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mobile Device</label>
    <nameField>
        <label>Mobile Device Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne/src/classes/VOD_MobileDeviceUtils.cls
public class  VOD_MobileDeviceUtils {
    public static void modifyMobileDeviceRecords(List<Id> userIds) {
         if(System.isFuture() || System.isBatch()) {
             system.debug('modifyMobileDeviceRecordsSync runs');
             modifyMobileDeviceRecordsSync(userIds);
         } else {
             system.debug('modifyMobileDeviceRecordsFuture runs');
             modifyMobileDeviceRecordsFuture(userIds);
         }
        
    }
    
    public static void modifyMobileDeviceRecordsSync(List<Id> userIds) {
        List<Mobile_Device_vod__c> updateRecords = null;
        for (Id userId: userIds) {
            List<Mobile_Device_vod__c> mobileDeviceList = [Select Id, Active_vod__c, User_vod__c from Mobile_Device_vod__c WHERE User_vod__c =: userId];
            if (mobileDeviceList != null && mobileDeviceList.size() > 0) {
                updateRecords = new List<Mobile_Device_vod__c>();
                for (Mobile_Device_vod__c record:  mobileDeviceList) {
                     record.Active_vod__c = false;
                     updateRecords.add(record);
                }
            }
        }
        
        if (updateRecords  != null && updateRecords.size() > 0) {
            update updateRecords;
        }
    }
    
    @future
    public static void modifyMobileDeviceRecordsFuture(List<Id> userIds) {
        modifyMobileDeviceRecordsSync(userIds);
    }
}